-- Migration: 007_seed_stories.sql
-- Description: Seed sample stories for testing the interactive reader gating and flashcard system.

-- Seed stories
INSERT INTO public.stories (
    title_ko,
    title_id,
    title_en,
    content_ko,
    content_id,
    content_en,
    level,
    category,
    cover_image_url,
    is_published,
    content_tokens
) VALUES
(
    '내 친구 지우',
    'Teman Baikku, Jiwoo',
    'My Friend Jiwoo',
    '지우는 내 친구입니다. 지우는 한국 사람입니다. 우리는 매일 같이 공부합니다. 지우는 한국어를 가르쳐 줍니다. 나는 지우를 좋아합니다.',
    'Jiwoo adalah teman saya. Jiwoo adalah orang Korea. Kami belajar bersama setiap hari. Jiwoo mengajarkan bahasa Korea (kepada saya). Saya menyukai Jiwoo.',
    'Jiwoo is my friend. Jiwoo is Korean. We study together every day. Jiwoo teaches me Korean. I like Jiwoo.',
    'beginner',
    'daily_life',
    'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
        {"t": "지우는", "l": "지우"}, {"t": " "},
        {"t": "내", "l": "나"}, {"t": " "},
        {"t": "친구입니다", "l": "친구"}, {"t": "."}, {"t": " "},
        {"t": "지우는", "l": "지우"}, {"t": " "},
        {"t": "한국", "l": "한국"}, {"t": " "},
        {"t": "사람입니다", "l": "사람"}, {"t": "."}, {"t": " "},
        {"t": "우리는", "l": "우리"}, {"t": " "},
        {"t": "매일", "l": "매일"}, {"t": " "},
        {"t": "같이", "l": "같이"}, {"t": " "},
        {"t": "공부합니다", "l": "공부하다"}, {"t": "."}, {"t": " "},
        {"t": "지우는", "l": "지우"}, {"t": " "},
        {"t": "한국어를", "l": "한국어"}, {"t": " "},
        {"t": "가르쳐", "l": "가르치다"}, {"t": " "},
        {"t": "줍니다", "l": "주다"}, {"t": "."}, {"t": " "},
        {"t": "나는", "l": "나"}, {"t": " "},
        {"t": "지우를", "l": "지우"}, {"t": " "},
        {"t": "좋아합니다", "l": "좋아하다"}, {"t": "."}
    ]'::jsonb
),
(
    '서울에서의 첫 가을',
    'Musim Gugur Pertama di Seoul',
    'First Autumn in Seoul',
    '저는 작년 가을에 서울에 왔습니다. 서울의 가을은 날씨가 선선하고 하늘이 아주 파랗습니다. 단풍이 예쁘게 들어서 공원을 산책하기 좋습니다. 경복궁에 가서 한복을 입고 사진을 찍었습니다. 그때 먹은 길거리 음식이 아직도 생각납니다.',
    'Saya datang ke Seoul musim gugur tahun lalu. Musim gugur di Seoul cuacanya sejuk dan langitnya sangat biru. Karena daun-daun berubah warna menjadi indah (dan berguguran), berjalan-jalan di taman terasa menyenangkan. Saya pergi ke Istana Gyeongbokgung, memakai Hanbok, dan berfoto. Saya masih teringat jajanan jalanan yang saya makan saat itu.',
    'I came to Seoul last autumn. Autumn in Seoul is cool and the sky is very blue. The autumn foliage is so beautiful that it is nice to walk in the park. I went to Gyeongbokgung Palace, wore Hanbok, and took pictures. I still remember the street food I ate back then.',
    'intermediate',
    'travel',
    'https://images.unsplash.com/photo-1542044896530-05d85be9b11a?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
        {"t": "저는", "l": "저"}, {"t": " "},
        {"t": "작년", "l": "작년"}, {"t": " "},
        {"t": "가을에", "l": "가을"}, {"t": " "},
        {"t": "서울에", "l": "서울"}, {"t": " "},
        {"t": "왔습니다", "l": "오다"}, {"t": "."}, {"t": " "},
        {"t": "서울의", "l": "서울"}, {"t": " "},
        {"t": "가을은", "l": "가을"}, {"t": " "},
        {"t": "날씨가", "l": "날씨"}, {"t": " "},
        {"t": "선선하고", "l": "선선하다"}, {"t": " "},
        {"t": "하늘이", "l": "하늘"}, {"t": " "},
        {"t": "아주", "l": "아주"}, {"t": " "},
        {"t": "파랗습니다", "l": "파랗다"}, {"t": "."}, {"t": " "},
        {"t": "단풍이", "l": "단풍"}, {"t": " "},
        {"t": "예쁘게", "l": "예쁘다"}, {"t": " "},
        {"t": "들어서", "l": "들다"}, {"t": " "},
        {"t": "공원을", "l": "공원"}, {"t": " "},
        {"t": "산책하기", "l": "산책하다"}, {"t": " "},
        {"t": "좋습니다", "l": "좋다"}, {"t": "."}, {"t": " "},
        {"t": "경복궁에", "l": "경복궁"}, {"t": " "},
        {"t": "가서", "l": "가다"}, {"t": " "},
        {"t": "한복을", "l": "한복"}, {"t": " "},
        {"t": "입고", "l": "입다"}, {"t": " "},
        {"t": "사진을", "l": "사진"}, {"t": " "},
        {"t": "찍었습니다", "l": "찍다"}, {"t": "."}, {"t": " "},
        {"t": "그때", "l": "그때"}, {"t": " "},
        {"t": "먹은", "l": "먹다"}, {"t": " "},
        {"t": "길거리", "l": "길거리"}, {"t": " "},
        {"t": "음식이", "l": "음식"}, {"t": " "},
        {"t": "아직도", "l": "아직도"}, {"t": " "},
        {"t": "생각납니다", "l": "생각나다"}, {"t": "."}
    ]'::jsonb
),
(
    '효도와 한국의 현대 사회',
    'Bakti Orang Tua dan Masyarakat Modern Korea',
    'Filial Piety and Modern Korean Society',
    '전통적으로 한국 사회에서 효도는 가장 중요한 유교적 가치 중 하나였습니다. 자식은 부모님을 정성껏 모시고 봉양해야 한다는 책임감이 강했습니다. 그러나 급격한 산업화와 핵가족화로 인해 현대 사회에서 효도의 개념과 실천 방식이 크게 변화하고 있습니다. 오늘날 젊은 세대는 부모님과의 정서적 교류를 중요시하는 반면, 경제적 부양에 대해서는 국가나 사회의 지원이 병행되어야 한다고 생각하는 경향이 뚜렷해지고 있습니다.',
    'Secara tradisional, dalam masyarakat Korea, bakti kepada orang tua (hyodo) adalah salah satu nilai Konfusianisme yang paling penting. Anak-anak memiliki rasa tanggung jawab yang kuat untuk merawat dan menafkahi orang tua mereka dengan tulus. Namun, akibat industrialisasi yang cepat dan pembentukan keluarga inti, konsep dan metode mempraktikkan bakti dalam masyarakat modern telah berubah secara signifikan. Saat ini, generasi muda menganggap penting interaksi emosional dengan orang tua, sementara ada kecenderungan yang jelas untuk berpikir bahwa tunjangan ekonomi harus didukung bersama oleh negara atau masyarakat.',
    'Traditionally, in Korean society, filial piety (hyodo) was one of the most important Confucian values. Children had a strong sense of responsibility to serve and support their parents sincerely. However, due to rapid industrialization and nuclearization of families, the concept and practice of filial piety in modern society are undergoing significant changes. While today''s younger generation emphasizes emotional interaction with their parents, there is a clear trend toward thinking that economic support should be coupled with state or social support.',
    'advanced',
    'culture',
    'https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
        {"t": "전통적으로", "l": "전통적"}, {"t": " "},
        {"t": "한국", "l": "한국"}, {"t": " "},
        {"t": "사회에서", "l": "사회"}, {"t": " "},
        {"t": "효도는", "l": "효도"}, {"t": " "},
        {"t": "가장", "l": "가장"}, {"t": " "},
        {"t": "중요한", "l": "중요하다"}, {"t": " "},
        {"t": "유교적", "l": "유교적"}, {"t": " "},
        {"t": "가치", "l": "가치"}, {"t": " "},
        {"t": "중", "l": "중"}, {"t": " "},
        {"t": "하나였습니다", "l": "하나"}, {"t": "."}, {"t": " "},
        {"t": "자식은", "l": "자식"}, {"t": " "},
        {"t": "부모님을", "l": "부모님"}, {"t": " "},
        {"t": "정성껏", "l": "정성껏"}, {"t": " "},
        {"t": "모시고", "l": "모시다"}, {"t": " "},
        {"t": "봉양해야", "l": "봉양하다"}, {"t": " "},
        {"t": "한다는", "l": "하다"}, {"t": " "},
        {"t": "책임감이", "l": "책임감"}, {"t": " "},
        {"t": "강했습니다", "l": "강하다"}, {"t": "."}, {"t": " "},
        {"t": "그러나", "l": "그러나"}, {"t": " "},
        {"t": "급격한", "l": "급격하다"}, {"t": " "},
        {"t": "산업화와", "l": "산업화"}, {"t": " "},
        {"t": "핵가족화로", "l": "핵가족화"}, {"t": " "},
        {"t": "인해", "l": "인하다"}, {"t": " "},
        {"t": "현대", "l": "현대"}, {"t": " "},
        {"t": "사회에서", "l": "사회"}, {"t": " "},
        {"t": "효도의", "l": "효도"}, {"t": " "},
        {"t": "개념과", "l": "개념"}, {"t": " "},
        {"t": "실천", "l": "실천"}, {"t": " "},
        {"t": "방식이", "l": "방식"}, {"t": " "},
        {"t": "크게", "l": "크다"}, {"t": " "},
        {"t": "변화하고", "l": "변화하다"}, {"t": " "},
        {"t": "있습니다", "l": "있다"}, {"t": "."}, {"t": " "},
        {"t": "오늘날", "l": "오늘날"}, {"t": " "},
        {"t": "젊은", "l": "젊다"}, {"t": " "},
        {"t": "세대는", "l": "세대"}, {"t": " "},
        {"t": "부모님과의", "l": "부모님"}, {"t": " "},
        {"t": "정서적", "l": "정서적"}, {"t": " "},
        {"t": "교류를", "l": "교류"}, {"t": " "},
        {"t": "중요시하는", "l": "중요시하다"}, {"t": " "},
        {"t": "반면", "l": "반면"}, {"t": ","}, {"t": " "},
        {"t": "경제적", "l": "경제적"}, {"t": " "},
        {"t": "부양에", "l": "부양"}, {"t": " "},
        {"t": "대해서는", "l": "대하다"}, {"t": " "},
        {"t": "국가나", "l": "국가"}, {"t": " "},
        {"t": "사회의", "l": "사회"}, {"t": " "},
        {"t": "지원이", "l": "지원"}, {"t": " "},
        {"t": "병행되어야", "l": "병행되다"}, {"t": " "},
        {"t": "한다고", "l": "하다"}, {"t": " "},
        {"t": "생각하는", "l": "생각하다"}, {"t": " "},
        {"t": "경향이", "l": "경향"}, {"t": " "},
        {"t": "뚜렷해지고", "l": "뚜렷해지다"}, {"t": " "},
        {"t": "있습니다", "l": "있다"}, {"t": "."}
    ]'::jsonb
);
