-- Migration: 012_add_more_stories.sql
-- Description: Add 3 intermediate and 3 advanced stories with interactive word tokens

INSERT INTO public.stories (
    title_ko,
    title_id,
    title_en,
    content_ko,
    content_id,
    content_en,
    level,
    category,
    cover_image_url,
    is_published,
    content_tokens
) VALUES
(
    '한국의 배달 문화',
    'Budaya Pengiriman Makanan di Korea',
    'Delivery Culture in Korea',
    '한국은 배달 문화가 세계적으로 유명한 나라예요. 스마트폰 앱만 있으면 언제 어디서나 음식을 주문할 수 있어요. 한밤중이나 공원 같은 야외에서도 배달이 가능해요. 짜장면, 치킨, 피자뿐만 아니라 한식과 커피도 배달해 줘요. 배달 속도도 아주 빠르고 편리해요. 최근에는 일회용품 대신 다회용기를 사용하는 친환경 배달도 늘어나고 있어요. 한국에 여행을 오면 한강 공원에서 치킨을 배달시켜 먹는 것을 꼭 추천해요.',
    'Korea adalah negara yang budaya pengirimannya (delivery) terkenal di seluruh dunia. Hanya dengan aplikasi ponsel pintar, Anda bisa memesan makanan kapan saja dan di mana saja. Pengiriman tetap dapat dilakukan saat tengah malam maupun di luar ruangan seperti taman. Tidak hanya jjajangmyeon, ayam, dan pizza, tetapi makanan Korea dan kopi juga diantarkan. Kecepatan pengirimannya pun sangat cepat dan nyaman. Baru-baru ini, pengiriman ramah lingkungan yang menggunakan wadah guna ulang alih-alih wadah sekali pakai juga meningkat. Jika Anda bepergian ke Korea, sangat direkomendasikan untuk memesan dan menyantap ayam di Taman Sungai Han.',
    'Korea is a country whose delivery culture is famous worldwide. With just a smartphone app, you can order food anytime, anywhere. Delivery is possible even at midnight or outdoors in places like parks. They deliver not only jjajangmyeon, chicken, and pizza, but also Korean food and coffee. The delivery speed is very fast and convenient. Recently, eco-friendly delivery using reusable containers instead of disposable ones is also increasing. If you travel to Korea, I highly recommend ordering and eating chicken at the Hangang Park.',
    'intermediate',
    'food',
    'https://images.unsplash.com/photo-1526367790999-0150786486a9?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "한국은", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "배달", "l": "배달"},
  {"t": " ", "l": " "},
  {"t": "문화가", "l": "문화"},
  {"t": " ", "l": " "},
  {"t": "세계적으로", "l": "세계적"},
  {"t": " ", "l": " "},
  {"t": "유명한", "l": "유명하다"},
  {"t": " ", "l": " "},
  {"t": "나라예요", "l": "나라"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "스마트폰", "l": "스마트폰"},
  {"t": " ", "l": " "},
  {"t": "앱만", "l": "앱"},
  {"t": " ", "l": " "},
  {"t": "있으면", "l": "있다"},
  {"t": " ", "l": " "},
  {"t": "언제", "l": "언제"},
  {"t": " ", "l": " "},
  {"t": "어디서나", "l": "어디서나"},
  {"t": " ", "l": " "},
  {"t": "음식을", "l": "음식"},
  {"t": " ", "l": " "},
  {"t": "주문할", "l": "주문하다"},
  {"t": " ", "l": " "},
  {"t": "수", "l": "수"},
  {"t": " ", "l": " "},
  {"t": "있어요", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "한밤중이나", "l": "한밤중"},
  {"t": " ", "l": " "},
  {"t": "공원", "l": "공원"},
  {"t": " ", "l": " "},
  {"t": "같은", "l": "같다"},
  {"t": " ", "l": " "},
  {"t": "야외에서도", "l": "야외"},
  {"t": " ", "l": " "},
  {"t": "배달이", "l": "배달"},
  {"t": " ", "l": " "},
  {"t": "가능해요", "l": "가능하다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "짜장면", "l": "짜장면"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "치킨", "l": "치킨"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "피자뿐만", "l": "피자"},
  {"t": " ", "l": " "},
  {"t": "아니라", "l": "아니다"},
  {"t": " ", "l": " "},
  {"t": "한식과", "l": "한식"},
  {"t": " ", "l": " "},
  {"t": "커피도", "l": "커피"},
  {"t": " ", "l": " "},
  {"t": "배달해", "l": "배달하다"},
  {"t": " ", "l": " "},
  {"t": "줘요", "l": "주다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "배달", "l": "배달"},
  {"t": " ", "l": " "},
  {"t": "속도도", "l": "속도"},
  {"t": " ", "l": " "},
  {"t": "아주", "l": "아주"},
  {"t": " ", "l": " "},
  {"t": "빠르고", "l": "빠르다"},
  {"t": " ", "l": " "},
  {"t": "편리해요", "l": "편리하다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "최근에는", "l": "최근"},
  {"t": " ", "l": " "},
  {"t": "일회용품", "l": "일회용품"},
  {"t": " ", "l": " "},
  {"t": "대신", "l": "대신"},
  {"t": " ", "l": " "},
  {"t": "다회용기를", "l": "다회용기"},
  {"t": " ", "l": " "},
  {"t": "사용하는", "l": "사용하다"},
  {"t": " ", "l": " "},
  {"t": "친환경", "l": "친환경"},
  {"t": " ", "l": " "},
  {"t": "배달도", "l": "배달"},
  {"t": " ", "l": " "},
  {"t": "늘어나고", "l": "늘어나다"},
  {"t": " ", "l": " "},
  {"t": "있어요", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "한국에", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "여행을", "l": "여행"},
  {"t": " ", "l": " "},
  {"t": "오면", "l": "오다"},
  {"t": " ", "l": " "},
  {"t": "한강", "l": "한강"},
  {"t": " ", "l": " "},
  {"t": "공원에서", "l": "공원"},
  {"t": " ", "l": " "},
  {"t": "치킨을", "l": "치킨"},
  {"t": " ", "l": " "},
  {"t": "배달시켜", "l": "배달시키다"},
  {"t": " ", "l": " "},
  {"t": "먹는", "l": "먹다"},
  {"t": " ", "l": " "},
  {"t": "것을", "l": "것"},
  {"t": " ", "l": " "},
  {"t": "꼭", "l": "꼭"},
  {"t": " ", "l": " "},
  {"t": "추천해요", "l": "추천하다"},
  {"t": ".", "l": "."}
]'::jsonb
),
(
    '한국의 분리수거',
    'Pemilahan Sampah di Korea',
    'Recycling in Korea',
    '한국은 쓰레기 분리수거를 아주 철저하게 하는 나라예요. 쓰레기는 크게 일반 쓰레기, 음식물 쓰레기, 그리고 재활용품으로 나누어 버려요. 재활용품도 종이, 플라스틱, 유리, 캔 등으로 자세히 분류해야 해요. 아파트마다 분리수거를 하는 요일과 장소가 정해져 있어요. 만약 분리수거를 잘못하면 벌금을 낼 수도 있어요. 처음에는 조금 복잡하고 어렵게 느껴질 수 있지만, 환경을 보호하기 위해 꼭 필요한 일이에요. 한국 사람들은 깨끗한 환경을 위해 분리수거를 열심히 실천하고 있어요.',
    'Korea adalah negara yang melakukan pemilahan sampah dengan sangat teliti. Sampah secara garis besar dibagi menjadi sampah umum, sampah makanan, dan barang daur ulang. Barang daur ulang juga harus dikelompokkan secara detail ke dalam kertas, plastik, kaca, kaleng, dan lain-lain. Setiap apartemen memiliki hari dan tempat pemilahan sampah yang telah ditentukan. Jika Anda melakukan pemilahan sampah dengan salah, Anda bisa dikenai denda. Awalnya mungkin terasa agak rumit dan sulit, tetapi ini adalah hal yang sangat penting untuk melindungi lingkungan. Orang Korea aktif mempraktikkan pemilahan sampah dengan giat demi lingkungan yang bersih.',
    'Korea is a country that practices trash recycling very thoroughly. Waste is divided into general waste, food waste, and recyclables. Recyclables must be categorized into paper, plastic, glass, cans, etc. Each apartment has designated days and locations for recycling. If you recycle incorrectly, you might pay a fine. It may feel a bit complicated and difficult at first, but it is necessary to protect the environment. Korean people actively practice recycling for a clean environment.',
    'intermediate',
    'daily_life',
    'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "한국은", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "쓰레기", "l": "쓰레기"},
  {"t": " ", "l": " "},
  {"t": "분리수거를", "l": "분리수거"},
  {"t": " ", "l": " "},
  {"t": "아주", "l": "아주"},
  {"t": " ", "l": " "},
  {"t": "철저하게", "l": "철저하다"},
  {"t": " ", "l": " "},
  {"t": "하는", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "나라예요", "l": "나라"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "쓰레기는", "l": "쓰레기"},
  {"t": " ", "l": " "},
  {"t": "크게", "l": "크다"},
  {"t": " ", "l": " "},
  {"t": "일반", "l": "일반"},
  {"t": " ", "l": " "},
  {"t": "쓰레기", "l": "쓰레기"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "음식물", "l": "음식물"},
  {"t": " ", "l": " "},
  {"t": "쓰레기", "l": "쓰레기"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "그리고", "l": "그리고"},
  {"t": " ", "l": " "},
  {"t": "재활용품으로", "l": "재활용품"},
  {"t": " ", "l": " "},
  {"t": "나누어", "l": "나누다"},
  {"t": " ", "l": " "},
  {"t": "버려요", "l": "버리다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "재활용품도", "l": "재활용품"},
  {"t": " ", "l": " "},
  {"t": "종이", "l": "종이"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "플라스틱", "l": "플라스틱"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "유리", "l": "유리"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "캔", "l": "캔"},
  {"t": " ", "l": " "},
  {"t": "등으로", "l": "등"},
  {"t": " ", "l": " "},
  {"t": "자세히", "l": "자세하다"},
  {"t": " ", "l": " "},
  {"t": "분류해야", "l": "분류하다"},
  {"t": " ", "l": " "},
  {"t": "해요", "l": "하다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "아파트마다", "l": "아파트"},
  {"t": " ", "l": " "},
  {"t": "분리수거를", "l": "분리수거"},
  {"t": " ", "l": " "},
  {"t": "하는", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "요일과", "l": "요일"},
  {"t": " ", "l": " "},
  {"t": "장소가", "l": "장소"},
  {"t": " ", "l": " "},
  {"t": "정해져", "l": "정하다"},
  {"t": " ", "l": " "},
  {"t": "있어요", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "만약", "l": "만약"},
  {"t": " ", "l": " "},
  {"t": "분리수거를", "l": "분리수거"},
  {"t": " ", "l": " "},
  {"t": "잘못하면", "l": "잘못하다"},
  {"t": " ", "l": " "},
  {"t": "벌금을", "l": "벌금"},
  {"t": " ", "l": " "},
  {"t": "낼", "l": "내다"},
  {"t": " ", "l": " "},
  {"t": "수도", "l": "수도"},
  {"t": " ", "l": " "},
  {"t": "있어요", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "처음에는", "l": "처음"},
  {"t": " ", "l": " "},
  {"t": "조금", "l": "조금"},
  {"t": " ", "l": " "},
  {"t": "복잡하고", "l": "복잡하다"},
  {"t": " ", "l": " "},
  {"t": "어렵게", "l": "어렵다"},
  {"t": " ", "l": " "},
  {"t": "느껴질", "l": "느끼다"},
  {"t": " ", "l": " "},
  {"t": "수", "l": "수"},
  {"t": " ", "l": " "},
  {"t": "있지만", "l": "있다"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "환경을", "l": "환경"},
  {"t": " ", "l": " "},
  {"t": "보호하기", "l": "보호하다"},
  {"t": " ", "l": " "},
  {"t": "위해", "l": "위하다"},
  {"t": " ", "l": " "},
  {"t": "꼭", "l": "꼭"},
  {"t": " ", "l": " "},
  {"t": "필요한", "l": "필요하다"},
  {"t": " ", "l": " "},
  {"t": "일이에요", "l": "일"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "한국", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "사람들은", "l": "사람"},
  {"t": " ", "l": " "},
  {"t": "깨끗한", "l": "깨끗하다"},
  {"t": " ", "l": " "},
  {"t": "환경을", "l": "환경"},
  {"t": " ", "l": " "},
  {"t": "위해", "l": "위하다"},
  {"t": " ", "l": " "},
  {"t": "분리수거를", "l": "분리수거"},
  {"t": " ", "l": " "},
  {"t": "열심히", "l": "열심히"},
  {"t": " ", "l": " "},
  {"t": "실천하고", "l": "실천하다"},
  {"t": " ", "l": " "},
  {"t": "있어요", "l": "있다"},
  {"t": ".", "l": "."}
]'::jsonb
),
(
    '한국의 한옥 마을',
    'Desa Hanok di Korea',
    'Hanok Villages in Korea',
    '한옥은 한국의 전통 집이에요. 나무와 흙으로 만들어서 자연 친화적이고, 여름에는 시원하고 겨울에는 온돌 덕분에 따뜻해요. 서울의 북촌 한옥 마을이나 전주의 한옥 마을에 가면 아름다운 한옥들을 많이 볼 수 있어요. 이곳에서는 옛날 한국의 분위기를 느끼며 산책을 할 수 있어요. 한복을 빌려 입고 한옥을 배경으로 예쁜 사진을 찍는 관광객들이 아주 많아요. 전통 차를 마실 수 있는 찻집이나 한옥에서 직접 잠을 자는 체험 프로그램도 인기가 많아요.',
    'Hanok adalah rumah tradisional Korea. Dibuat dengan kayu dan tanah sehingga ramah lingkungan, terasa sejuk di musim panas dan hangat di musim dingin berkat ondol (pemanas lantai). Jika Anda pergi ke Desa Hanok Bukchon di Seoul atau Desa Hanok Jeonju, Anda bisa melihat banyak hanok yang indah. Di sini Anda bisa berjalan-jalan sambil merasakan suasana Korea zaman dahulu. Ada banyak sekali wisatawan yang menyewa hanbok lalu berfoto dengan latar belakang hanok. Kedai teh tradisional dan menginap di hanok juga sangat populer.',
    'Hanok is a traditional Korean house. Built with wood and clay, it is nature-friendly, cool in summer and warm in winter thanks to ondol (underfloor heating). If you go to Bukchon Hanok Village in Seoul or Jeonju Hanok Village, you can see many beautiful hanoks. Here, you can take a walk while feeling the atmosphere of old Korea. There are many tourists who rent and wear hanbok to take pictures with hanok as the background. Tea houses and overnight stays in a hanok are also very popular.',
    'intermediate',
    'travel',
    'https://images.unsplash.com/photo-1548115184-bc6544d06a58?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "한옥은", "l": "한옥"},
  {"t": " ", "l": " "},
  {"t": "한국의", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "전통", "l": "전통"},
  {"t": " ", "l": " "},
  {"t": "집이에요", "l": "이다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "나무와", "l": "나무"},
  {"t": " ", "l": " "},
  {"t": "흙으로", "l": "흙"},
  {"t": " ", "l": " "},
  {"t": "만들어서", "l": "만들다"},
  {"t": " ", "l": " "},
  {"t": "자연", "l": "자연"},
  {"t": " ", "l": " "},
  {"t": "친화적이고", "l": "친화적이다"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "여름에는", "l": "여름"},
  {"t": " ", "l": " "},
  {"t": "시원하고", "l": "시원하다"},
  {"t": " ", "l": " "},
  {"t": "겨울에는", "l": "겨울"},
  {"t": " ", "l": " "},
  {"t": "온돌", "l": "온돌"},
  {"t": " ", "l": " "},
  {"t": "덕분에", "l": "덕분이다"},
  {"t": " ", "l": " "},
  {"t": "따뜻해요", "l": "따뜻하다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "서울의", "l": "서울"},
  {"t": " ", "l": " "},
  {"t": "북촌", "l": "북촌"},
  {"t": " ", "l": " "},
  {"t": "한옥", "l": "한옥"},
  {"t": " ", "l": " "},
  {"t": "마을이나", "l": "마을"},
  {"t": " ", "l": " "},
  {"t": "전주의", "l": "전주"},
  {"t": " ", "l": " "},
  {"t": "한옥", "l": "한옥"},
  {"t": " ", "l": " "},
  {"t": "마을에", "l": "마을"},
  {"t": " ", "l": " "},
  {"t": "가면", "l": "가다"},
  {"t": " ", "l": " "},
  {"t": "아름다운", "l": "아름답다"},
  {"t": " ", "l": " "},
  {"t": "한옥들을", "l": "한옥"},
  {"t": " ", "l": " "},
  {"t": "많이", "l": "많이"},
  {"t": " ", "l": " "},
  {"t": "볼", "l": "보다"},
  {"t": " ", "l": " "},
  {"t": "수", "l": "수"},
  {"t": " ", "l": " "},
  {"t": "있어요", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "이곳에서는", "l": "이곳"},
  {"t": " ", "l": " "},
  {"t": "옛날", "l": "옛날"},
  {"t": " ", "l": " "},
  {"t": "한국의", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "분위기를", "l": "분위기"},
  {"t": " ", "l": " "},
  {"t": "느끼며", "l": "느끼다"},
  {"t": " ", "l": " "},
  {"t": "산책을", "l": "산책"},
  {"t": " ", "l": " "},
  {"t": "할", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "수", "l": "수"},
  {"t": " ", "l": " "},
  {"t": "있어요", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "한복을", "l": "한복"},
  {"t": " ", "l": " "},
  {"t": "빌려", "l": "빌리다"},
  {"t": " ", "l": " "},
  {"t": "입고", "l": "입다"},
  {"t": " ", "l": " "},
  {"t": "한옥을", "l": "한옥"},
  {"t": " ", "l": " "},
  {"t": "배경으로", "l": "배경"},
  {"t": " ", "l": " "},
  {"t": "예쁜", "l": "예쁘다"},
  {"t": " ", "l": " "},
  {"t": "사진을", "l": "사진"},
  {"t": " ", "l": " "},
  {"t": "찍는", "l": "찍다"},
  {"t": " ", "l": " "},
  {"t": "관광객들이", "l": "관광객"},
  {"t": " ", "l": " "},
  {"t": "아주", "l": "아주"},
  {"t": " ", "l": " "},
  {"t": "많아요", "l": "많다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "전통", "l": "전통"},
  {"t": " ", "l": " "},
  {"t": "차를", "l": "차"},
  {"t": " ", "l": " "},
  {"t": "마실", "l": "마시다"},
  {"t": " ", "l": " "},
  {"t": "수", "l": "수"},
  {"t": " ", "l": " "},
  {"t": "있는", "l": "있다"},
  {"t": " ", "l": " "},
  {"t": "찻집이나", "l": "찻집"},
  {"t": " ", "l": " "},
  {"t": "한옥에서", "l": "한옥"},
  {"t": " ", "l": " "},
  {"t": "직접", "l": "직접"},
  {"t": " ", "l": " "},
  {"t": "잠을", "l": "잠"},
  {"t": " ", "l": " "},
  {"t": "자는", "l": "자다"},
  {"t": " ", "l": " "},
  {"t": "체험", "l": "체험"},
  {"t": " ", "l": " "},
  {"t": "프로그램도", "l": "프로그램"},
  {"t": " ", "l": " "},
  {"t": "인기가", "l": "인기"},
  {"t": " ", "l": " "},
  {"t": "많아요", "l": "많다"},
  {"t": ".", "l": "."}
]'::jsonb
),
(
    '한국의 저출산 문제',
    'Masalah Rendahnya Angka Kelahiran di Korea',
    'Korea''s Low Birth Rate Issue',
    '대한민국은 세계에서 합계출산율이 가장 낮은 국가 중 하나로, 저출산 문제는 사회적 지속 가능성을 위협하는 심각한 위기로 부상했다. 이러한 현상의 주된 원인으로는 주거비 부담, 고용 불안정, 그리고 양육 및 사교육비에 대한 과도한 경제적 압박이 꼽힌다. 청년 세대는 결혼과 출산을 필수가 아닌 선택으로 인식하고 있으며, 자신의 경제적 자립과 삶의 질을 우선시하는 경향이 뚜렷해지고 있다. 정부는 저출산 극복을 위해 아동수당 지급, 육아휴직 확대, 공공주택 지원 등 다양한 정책적 대안을 제시해 왔으나 실질적인 효과는 미미한 실정이다. 문제의 근본적인 해결을 위해서는 일회성 지원을 넘어 일과 가정이 양립할 수 있는 양성평등한 근로 환경 조성과 사회적 안전망 강화가 병행되어야 한다. 인구 구조의 격변은 노동력 부족과 잠재성장률 하락으로 이어질 수 있으므로, 보다 구조적이고 장기적인 대책 마련이 시급하다.',
    'Republik Korea adalah salah satu negara dengan tingkat kesuburan total terendah di dunia, dan masalah rendahnya angka kelahiran telah muncul sebagai krisis serius yang mengancam keberlanjutan sosial. Penyebab utama termasuk beban biaya perumahan, ketidakstabilan pekerjaan, serta tekanan ekonomi berlebih untuk pengasuhan anak dan biaya bimbingan belajar swasta. Generasi muda memandang pernikahan dan kelahiran anak sebagai pilihan, bukan kewajiban, serta mengutamakan kemandirian ekonomi dan kualitas hidup mereka sendiri. Pemerintah menawarkan berbagai kebijakan seperti tunjangan anak, cuti pengasuhan anak, dan dukungan perumahan publik, namun dampaknya masih minim. Untuk menyelesaikan masalah ini secara mendasar, penyelarasan kehidupan kerja-keluarga dan penguatan jaring pengaman sosial harus dilakukan. Perubahan struktur populasi dapat menyebabkan kekurangan tenaga kerja, sehingga langkah-langkah struktural jangka panjang sangat mendesak.',
    'The Republic of Korea is one of the countries with the lowest total fertility rate in the world, and the low birth rate issue has emerged as a serious crisis threatening social sustainability. The primary causes include housing costs, employment instability, and excessive economic pressure related to child-rearing and private education. The younger generation perceives marriage and childbirth as options rather than necessities, prioritizing their own economic independence and quality of life. The government has presented various policy alternatives such as child allowance, parental leave, and housing support, but the practical effects remain minimal. To solve the problem fundamentally, creating a work-life balanced environment and strengthening the social safety net must be pursued. Population shifts can lead to labor shortages, making structural long-term countermeasures urgent.',
    'advanced',
    'society',
    'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "대한민국은", "l": "대한민국"},
  {"t": " ", "t": " "},
  {"t": "세계에서", "l": "세계"},
  {"t": " ", "t": " "},
  {"t": "합계출산율이", "l": "합계출산율"},
  {"t": " ", "t": " "},
  {"t": "가장", "l": "가장"},
  {"t": " ", "t": " "},
  {"t": "낮은", "l": "낮다"},
  {"t": " ", "t": " "},
  {"t": "국가", "l": "국가"},
  {"t": " ", "t": " "},
  {"t": "중", "l": "중"},
  {"t": " ", "t": " "},
  {"t": "하나로", "l": "하나"},
  {"t": ",", "t": ","},
  {"t": " ", "t": " "},
  {"t": "저출산", "l": "저출산"},
  {"t": " ", "t": " "},
  {"t": "문제는", "l": "문제"},
  {"t": " ", "t": " "},
  {"t": "사회적", "l": "사회적"},
  {"t": " ", "t": " "},
  {"t": "지속", "l": "지속"},
  {"t": " ", "t": " "},
  {"t": "가능성을", "l": "가능성"},
  {"t": " ", "t": " "},
  {"t": "위협하는", "l": "위협하다"},
  {"t": " ", "t": " "},
  {"t": "심각한", "l": "심각하다"},
  {"t": " ", "t": " "},
  {"t": "위기로", "l": "위기"},
  {"t": " ", "t": " "},
  {"t": "부상했다", "l": "부상하다"},
  {"t": ".", "t": "."},
  {"t": "\n", "t": "\n"},
  {"t": "이러한", "l": "이러한"},
  {"t": " ", "t": " "},
  {"t": "현상의", "l": "현상"},
  {"t": " ", "t": " "},
  {"t": "주된", "l": "주되다"},
  {"t": " ", "t": " "},
  {"t": "원인으로는", "l": "원인"},
  {"t": " ", "t": " "},
  {"t": "주거비", "l": "주거비"},
  {"t": " ", "t": " "},
  {"t": "부담", "l": "부담"},
  {"t": ",", "t": ","},
  {"t": " ", "t": " "},
  {"t": "고용", "l": "고용"},
  {"t": " ", "t": " "},
  {"t": "불안정", "l": "불안정"},
  {"t": ",", "t": ","},
  {"t": " ", "t": " "},
  {"t": "그리고", "l": "그리고"},
  {"t": " ", "t": " "},
  {"t": "양육", "l": "양육"},
  {"t": " ", "t": " "},
  {"t": "및", "l": "및"},
  {"t": " ", "t": " "},
  {"t": "사교육비에", "l": "사교육비"},
  {"t": " ", "t": " "},
  {"t": "대한", "l": "대하다"},
  {"t": " ", "t": " "},
  {"t": "과도한", "l": "과도하다"},
  {"t": " ", "t": " "},
  {"t": "경제적", "l": "경제적"},
  {"t": " ", "t": " "},
  {"t": "압박이", "l": "압박"},
  {"t": " ", "t": " "},
  {"t": "꼽힌다", "l": "꼽히다"},
  {"t": ".", "t": "."},
  {"t": "\n", "t": "\n"},
  {"t": "청년", "l": "청년"},
  {"t": " ", "t": " "},
  {"t": "세대는", "l": "세대"},
  {"t": " ", "t": " "},
  {"t": "결혼과", "l": "결혼"},
  {"t": " ", "t": " "},
  {"t": "출산을", "l": "출산"},
  {"t": " ", "t": " "},
  {"t": "필수가", "l": "필수"},
  {"t": " ", "t": " "},
  {"t": "아닌", "l": "아니다"},
  {"t": " ", "t": " "},
  {"t": "선택으로", "l": "선택"},
  {"t": " ", "t": " "},
  {"t": "인식하고", "l": "인식하다"},
  {"t": " ", "t": " "},
  {"t": "있으며", "l": "있다"},
  {"t": ",", "t": ","},
  {"t": " ", "t": " "},
  {"t": "자신의", "l": "자신"},
  {"t": " ", "t": " "},
  {"t": "경제적", "l": "경제적"},
  {"t": " ", "t": " "},
  {"t": "자립과", "l": "자립"},
  {"t": " ", "t": " "},
  {"t": "삶의", "l": "삶"},
  {"t": " ", "t": " "},
  {"t": "질을", "l": "질"},
  {"t": " ", "t": " "},
  {"t": "우선시하는", "l": "우선시하다"},
  {"t": " ", "t": " "},
  {"t": "경향이", "l": "경향"},
  {"t": " ", "t": " "},
  {"t": "뚜렷해지고", "l": "뚜렷해지다"},
  {"t": " ", "t": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "t": "."},
  {"t": "\n", "t": "\n"},
  {"t": "정부는", "l": "정부"},
  {"t": " ", "t": " "},
  {"t": "저출산", "l": "저출산"},
  {"t": " ", "t": " "},
  {"t": "극복을", "l": "극복"},
  {"t": " ", "t": " "},
  {"t": "위해", "l": "위하다"},
  {"t": " ", "t": " "},
  {"t": "아동수당", "l": "아동수당"},
  {"t": " ", "t": " "},
  {"t": "지급", "l": "지급"},
  {"t": ",", "t": ","},
  {"t": " ", "t": " "},
  {"t": "육아휴직", "l": "육아휴직"},
  {"t": " ", "t": " "},
  {"t": "확대", "l": "확대"},
  {"t": ",", "t": ","},
  {"t": " ", "t": " "},
  {"t": "공공주택", "l": "공공주택"},
  {"t": " ", "t": " "},
  {"t": "지원", "l": "지원"},
  {"t": " ", "t": " "},
  {"t": "등", "l": "등"},
  {"t": " ", "t": " "},
  {"t": "다양한", "l": "다양하다"},
  {"t": " ", "t": " "},
  {"t": "정책적", "l": "정책적"},
  {"t": " ", "t": " "},
  {"t": "대안을", "l": "대안"},
  {"t": " ", "t": " "},
  {"t": "제시해", "l": "제시하다"},
  {"t": " ", "t": " "},
  {"t": "왔으나", "l": "오다"},
  {"t": " ", "t": " "},
  {"t": "실질적인", "l": "실질적"},
  {"t": " ", "t": " "},
  {"t": "효과는", "l": "효과"},
  {"t": " ", "t": " "},
  {"t": "미미한", "l": "미미하다"},
  {"t": " ", "t": " "},
  {"t": "실정이다", "l": "실정"},
  {"t": ".", "t": "."},
  {"t": "\n", "t": "\n"},
  {"t": "문제의", "l": "문제"},
  {"t": " ", "t": " "},
  {"t": "근본적인", "l": "근본적"},
  {"t": " ", "t": " "},
  {"t": "해결을", "l": "해결"},
  {"t": " ", "t": " "},
  {"t": "위해서는", "l": "위하다"},
  {"t": " ", "t": " "},
  {"t": "일회성", "l": "일회성"},
  {"t": " ", "t": " "},
  {"t": "지원을", "l": "지원"},
  {"t": " ", "t": " "},
  {"t": "넘어", "l": "넘다"},
  {"t": " ", "t": " "},
  {"t": "일과", "l": "일"},
  {"t": " ", "t": " "},
  {"t": "가정이", "l": "가정"},
  {"t": " ", "t": " "},
  {"t": "양립할", "l": "양립하다"},
  {"t": " ", "t": " "},
  {"t": "수", "l": "수"},
  {"t": " ", "t": " "},
  {"t": "있는", "l": "있다"},
  {"t": " ", "t": " "},
  {"t": "양성평등한", "l": "양성평등하다"},
  {"t": " ", "t": " "},
  {"t": "근로", "l": "근로"},
  {"t": " ", "t": " "},
  {"t": "환경", "l": "환경"},
  {"t": " ", "t": " "},
  {"t": "조성과", "l": "조성"},
  {"t": " ", "t": " "},
  {"t": "사회적", "l": "사회적"},
  {"t": " ", "t": " "},
  {"t": "안전망", "l": "안전망"},
  {"t": " ", "t": " "},
  {"t": "강화가", "l": "강화"},
  {"t": " ", "t": " "},
  {"t": "병행되어야", "l": "병행하다"},
  {"t": " ", "t": " "},
  {"t": "한다", "l": "하다"},
  {"t": ".", "t": "."},
  {"t": "\n", "t": "\n"},
  {"t": "인구", "l": "인구"},
  {"t": " ", "t": " "},
  {"t": "구조의", "l": "구조"},
  {"t": " ", "t": " "},
  {"t": "격변은", "l": "격변"},
  {"t": " ", "t": " "},
  {"t": "노동력", "l": "노동력"},
  {"t": " ", "t": " "},
  {"t": "부족과", "l": "부족"},
  {"t": " ", "t": " "},
  {"t": "잠재성장률", "l": "잠재성장률"},
  {"t": " ", "t": " "},
  {"t": "하락으로", "l": "하락"},
  {"t": " ", "t": " "},
  {"t": "이어질", "l": "이어지다"},
  {"t": " ", "t": " "},
  {"t": "수", "l": "수"},
  {"t": " ", "t": " "},
  {"t": "있으므로", "l": "있다"},
  {"t": ",", "t": ","},
  {"t": " ", "t": " "},
  {"t": "보다", "l": "보다"},
  {"t": " ", "t": " "},
  {"t": "구조적이고", "l": "구조적이다"},
  {"t": " ", "t": " "},
  {"t": "장기적인", "l": "장기적"},
  {"t": " ", "t": " "},
  {"t": "대책", "l": "대책"},
  {"t": " ", "t": " "},
  {"t": "마련이", "l": "마련"},
  {"t": " ", "t": " "},
  {"t": "시급하다", "l": "시급하다"},
  {"t": ".", "t": "."}
]'::jsonb
),
(
    '스마트 시티와 미래 교통 시스템',
    'Smart City dan Sistem Transportasi Masa Depan',
    'Smart Cities and Future Transport Systems',
    '첨단 기술의 융합을 통해 도시의 문제를 해결하고 삶의 질을 향상시키는 스마트 시티 구축이 세계적인 흐름으로 자리 잡고 있다. 특히 인공지능과 사물인터넷 기술을 접목한 미래형 교통 시스템은 스마트 시티의 핵심 구성 요소이다. 자율주행 대중교통, 실시간 교통량 분석을 통한 신호 제어 시스템 등은 교통 혼잡을 완화하고 탄소 배출을 줄이는 데 크게 기여하고 있다. 이러한 교통 혁신은 스마트폰 앱 하나로 이동 수단의 예약부터 결제까지 일괄적으로 해결하는 마스(MaaS, Mobility as a Service)의 실현으로 구체화되고 있다. 대중교통, 공유 자전거, 전동 킥보드 등이 유기적으로 연결되어 도시민의 이동 편의성이 극대화되었다. 그러나 자율주행 차량의 안전성 확보, 개인정보 보호 문제, 그리고 디지털 소외 계층에 대한 배려 등 해결해야 할 과제들도 여전히 존재한다. 기술적 발전이 진정한 도시의 번영으로 이어지기 위해서는 인간 중심의 설계 철학을 바탕으로 규제 완화와 사회적 안전 기준 수립이 균형 있게 이루어져야 할 것이다.',
    'Pembangunan kota pintar (smart city) yang menyelesaikan masalah perkotaan dan meningkatkan kualitas hidup melalui perpaduan teknologi mutakhir telah menjadi tren global. Secara khusus, sistem transportasi masa depan yang menggabungkan AI dan IoT merupakan komponen inti. Transportasi umum otonom dan sistem kontrol lampu lalu lintas melalui analisis arus lalu lintas waktu nyata berkontribusi besar meredakan kemacetan dan mengurangi emisi karbon. Inovasi ini diwujudkan dengan realisasi MaaS (Mobility as a Service) yang menyelesaikan pemesanan hingga pembayaran perjalanan sekaligus dengan satu aplikasi. Namun, tantangan seperti keselamatan kendaraan otonom, perlindungan informasi pribadi, dan perhatian terhadap kelas terpinggirkan secara digital tetap ada. Pelonggaran regulasi dan penetapan standar keselamatan harus berjalan seimbang berdasarkan filosofi desain yang berpusat pada manusia.',
    'Building smart cities to solve urban problems and improve quality of life through the convergence of advanced technologies is becoming a global trend. In particular, future-oriented transport systems incorporating AI and IoT are core components. Autonomous public transit and real-time traffic signal control systems contribute significantly to alleviating traffic congestion and reducing carbon emissions. This transport innovation is being embodied through the realization of MaaS (Mobility as a Service), which handles reservations to payments with a single app. Public transit, shared bicycles, and electric scooters are connected, maximizing mobility convenience. However, challenges like ensuring the safety of autonomous vehicles, data privacy, and digital exclusion still exist. Deregulation and safety standards must be balanced based on human-centered design.',
    'advanced',
    'technology',
    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "첨단", "l": "첨단"},
  {"t": " ", "l": " "},
  {"t": "기술", "l": "기술"},
  {"t": "의", "l": "의"},
  {"t": " ", "l": " "},
  {"t": "융합", "l": "융합"},
  {"t": "을", "l": "을"},
  {"t": " ", "l": " "},
  {"t": "통해", "l": "통하다"},
  {"t": " ", "l": " "},
  {"t": "도시", "l": "도시"},
  {"t": "의", "l": "의"},
  {"t": " ", "l": " "},
  {"t": "문제", "l": "문제"},
  {"t": "를", "l": "를"},
  {"t": " ", "l": " "},
  {"t": "해결", "l": "해결"},
  {"t": "하고", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "삶", "l": "삶"},
  {"t": "의", "l": "의"},
  {"t": " ", "l": " "},
  {"t": "질", "l": "질"},
  {"t": "을", "l": "을"},
  {"t": " ", "l": " "},
  {"t": "향상", "l": "향상"},
  {"t": "시키는", "l": "시키다"},
  {"t": " ", "l": " "},
  {"t": "스마트", "l": "스마트"},
  {"t": " ", "l": " "},
  {"t": "시티", "l": "시티"},
  {"t": " ", "l": " "},
  {"t": "구축", "l": "구축"},
  {"t": "이", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "세계", "l": "세계"},
  {"t": "적", "l": "적"},
  {"t": "인", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "흐름", "l": "흐름"},
  {"t": "으로", "l": "으로"},
  {"t": " ", "l": " "},
  {"t": "자리", "l": "자리"},
  {"t": " ", "l": " "},
  {"t": "잡고", "l": "잡다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "특히", "l": "특히"},
  {"t": " ", "l": " "},
  {"t": "인공지능", "l": "인공지능"},
  {"t": "과", "l": "과"},
  {"t": " ", "l": " "},
  {"t": "사물인터넷", "l": "사물인터넷"},
  {"t": " ", "l": " "},
  {"t": "기술", "l": "기술"},
  {"t": "을", "l": "을"},
  {"t": " ", "l": " "},
  {"t": "접목", "l": "접목"},
  {"t": "한", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "미래", "l": "미래"},
  {"t": "형", "l": "형"},
  {"t": " ", "l": " "},
  {"t": "교통", "l": "교통"},
  {"t": " ", "l": " "},
  {"t": "시스템", "l": "시스템"},
  {"t": "은", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "스마트", "l": "스마트"},
  {"t": " ", "l": " "},
  {"t": "시티", "l": "시티"},
  {"t": "의", "l": "의"},
  {"t": " ", "l": " "},
  {"t": "핵심", "l": "핵심"},
  {"t": " ", "l": " "},
  {"t": "구성", "l": "구성"},
  {"t": " ", "l": " "},
  {"t": "요소", "l": "요소"},
  {"t": "이다", "l": "이다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "자율주행", "l": "자율주행"},
  {"t": " ", "l": " "},
  {"t": "대중교통", "l": "대중교통"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "실시간", "l": "실시간"},
  {"t": " ", "l": " "},
  {"t": "교통량", "l": "교통량"},
  {"t": " ", "l": " "},
  {"t": "분석", "l": "분석"},
  {"t": "을", "l": "을"},
  {"t": " ", "l": " "},
  {"t": "통한", "l": "통하다"},
  {"t": " ", "l": " "},
  {"t": "신호", "l": "신호"},
  {"t": " ", "l": " "},
  {"t": "제어", "l": "제어"},
  {"t": " ", "l": " "},
  {"t": "시스템", "l": "시스템"},
  {"t": " ", "l": " "},
  {"t": "등", "l": "등"},
  {"t": "은", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "교통", "l": "교통"},
  {"t": " ", "l": " "},
  {"t": "혼잡", "l": "혼잡"},
  {"t": "을", "l": "을"},
  {"t": " ", "l": " "},
  {"t": "완화", "l": "완화"},
  {"t": "하고", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "탄소", "l": "탄소"},
  {"t": " ", "l": " "},
  {"t": "배출", "l": "배출"},
  {"t": "을", "l": "을"},
  {"t": " ", "l": " "},
  {"t": "줄이는", "l": "줄이다"},
  {"t": " ", "l": " "},
  {"t": "데", "l": "데"},
  {"t": " ", "l": " "},
  {"t": "크게", "l": "크게"},
  {"t": " ", "l": " "},
  {"t": "기여", "l": "기여"},
  {"t": "하고", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "이러한", "l": "이러한"},
  {"t": " ", "l": " "},
  {"t": "교통", "l": "교통"},
  {"t": " ", "l": " "},
  {"t": "혁신", "l": "혁신"},
  {"t": "은", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "스마트폰", "l": "스마트폰"},
  {"t": " ", "l": " "},
  {"t": "앱", "l": "앱"},
  {"t": " ", "l": " "},
  {"t": "하나", "l": "하나"},
  {"t": "로", "l": "로"},
  {"t": " ", "l": " "},
  {"t": "이동", "l": "이동"},
  {"t": " ", "l": " "},
  {"t": "수단", "l": "수단"},
  {"t": "의", "l": "의"},
  {"t": " ", "l": " "},
  {"t": "예약", "l": "예약"},
  {"t": "부터", "l": "부터"},
  {"t": " ", "l": " "},
  {"t": "결제", "l": "결제"},
  {"t": "까지", "l": "까지"},
  {"t": " ", "l": " "},
  {"t": "일괄", "l": "일괄"},
  {"t": "적으로", "l": "적으로"},
  {"t": " ", "l": " "},
  {"t": "해결", "l": "해결"},
  {"t": "하는", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "마스", "l": "마스"},
  {"t": "(", "l": "("},
  {"t": "MaaS", "l": "MaaS"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "Mobility", "l": "Mobility"},
  {"t": " ", "l": " "},
  {"t": "as", "l": "as"},
  {"t": " ", "l": " "},
  {"t": "a", "l": "a"},
  {"t": " ", "l": " "},
  {"t": "Service", "l": "Service"},
  {"t": ")", "l": ")"},
  {"t": "의", "l": "의"},
  {"t": " ", "l": " "},
  {"t": "실현", "l": "실현"},
  {"t": "으로", "l": "으로"},
  {"t": " ", "l": " "},
  {"t": "구체화", "l": "구체화"},
  {"t": "되고", "l": "되다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "대중교통", "l": "대중교통"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "공유", "l": "공유"},
  {"t": " ", "l": " "},
  {"t": "자전거", "l": "자전거"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "전동", "l": "전동"},
  {"t": " ", "l": " "},
  {"t": "킥보드", "l": "킥보드"},
  {"t": " ", "l": " "},
  {"t": "등", "l": "등"},
  {"t": "이", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "유기", "l": "유기"},
  {"t": "적으로", "l": "적으로"},
  {"t": " ", "l": " "},
  {"t": "연결", "l": "연결"},
  {"t": "되어", "l": "되다"},
  {"t": " ", "l": " "},
  {"t": "도시민", "l": "도시민"},
  {"t": "의", "l": "의"},
  {"t": " ", "l": " "},
  {"t": "이동", "l": "이동"},
  {"t": " ", "l": " "},
  {"t": "편의성", "l": "편의성"},
  {"t": "이", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "극대화", "l": "극대화"},
  {"t": "되었다", "l": "되다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "그러나", "l": "그러나"},
  {"t": " ", "l": " "},
  {"t": "자율주행", "l": "자율주행"},
  {"t": " ", "l": " "},
  {"t": "차량", "l": "차량"},
  {"t": "의", "l": "의"},
  {"t": " ", "l": " "},
  {"t": "안전성", "l": "안전성"},
  {"t": " ", "l": " "},
  {"t": "확보", "l": "확보"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "개인정보", "l": "개인정보"},
  {"t": " ", "l": " "},
  {"t": "보호", "l": "보호"},
  {"t": " ", "l": " "},
  {"t": "문제", "l": "문제"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "그리고", "l": "그리고"},
  {"t": " ", "l": " "},
  {"t": "디지털", "l": "디지털"},
  {"t": " ", "l": " "},
  {"t": "소외", "l": "소외"},
  {"t": " ", "l": " "},
  {"t": "계층", "l": "계층"},
  {"t": "에", "l": "에"},
  {"t": " ", "l": " "},
  {"t": "대한", "l": "대하다"},
  {"t": " ", "l": " "},
  {"t": "배려", "l": "배려"},
  {"t": " ", "l": " "},
  {"t": "등", "l": "등"},
  {"t": " ", "l": " "},
  {"t": "해결", "l": "해결"},
  {"t": "해야", "l": "해야"},
  {"t": " ", "l": " "},
  {"t": "할", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "과제", "l": "과제"},
  {"t": "들도", "l": "도"},
  {"t": " ", "l": " "},
  {"t": "여전히", "l": "여전히"},
  {"t": " ", "l": " "},
  {"t": "존재", "l": "존재"},
  {"t": "한다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "기술", "l": "기술"},
  {"t": "적", "l": "적"},
  {"t": " ", "l": " "},
  {"t": "발전", "l": "발전"},
  {"t": "이", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "진정한", "l": "진정한"},
  {"t": " ", "l": " "},
  {"t": "도시", "l": "도시"},
  {"t": "의", "l": "의"},
  {"t": " ", "l": " "},
  {"t": "번영", "l": "번영"},
  {"t": "으로", "l": "으로"},
  {"t": " ", "l": " "},
  {"t": "이어지기", "l": "이어지다"},
  {"t": " ", "l": " "},
  {"t": "위해서", "l": "위하다"},
  {"t": "는", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "인간", "l": "인간"},
  {"t": " ", "l": " "},
  {"t": "중심", "l": "중심"},
  {"t": "의", "l": "의"},
  {"t": " ", "l": " "},
  {"t": "설계", "l": "설계"},
  {"t": " ", "l": " "},
  {"t": "철학", "l": "철학"},
  {"t": "을", "l": "을"},
  {"t": " ", "l": " "},
  {"t": "바탕", "l": "바탕"},
  {"t": "으로", "l": "으로"},
  {"t": " ", "l": " "},
  {"t": "규제", "l": "규제"},
  {"t": " ", "l": " "},
  {"t": "완화", "l": "완화"},
  {"t": "와", "l": "와"},
  {"t": " ", "l": " "},
  {"t": "사회", "l": "사회"},
  {"t": "적", "l": "적"},
  {"t": " ", "l": " "},
  {"t": "안전", "l": "안전"},
  {"t": " ", "l": " "},
  {"t": "기준", "l": "기준"},
  {"t": " ", "l": " "},
  {"t": "수립", "l": "수립"},
  {"t": "이", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "균형", "l": "균형"},
  {"t": "있게", "l": "있게"},
  {"t": " ", "l": " "},
  {"t": "이루어져야", "l": "이루어지다"},
  {"t": " ", "l": " "},
  {"t": "할", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "것", "l": "것"},
  {"t": "이다", "l": "이다"},
  {"t": ".", "l": "."}
]'::jsonb
),
(
    '한복의 역사와 현대적 변신',
    'Sejarah Hanbok dan Transformasi Modernnya',
    'History and Modern Transformation of Hanbok',
    '한복은 오랜 역사 동안 한국인과 함께하며 시대의 문화적 가치와 미의식을 담아온 전통 복식이다. 기본적으로 상의와 하의가 분리된 구조로 되어 있어 활동성이 뛰어나며, 평면 재단법을 사용하여 입었을 때 자연스러운 선의 흐름과 여유로운 실루엣을 만들어내는 것이 특징이다. 전통 한복의 색채는 음양오행 사상에 기반한 오방색을 주로 사용하여 자연과의 조화를 지향했다. 현대에 이르러 한복은 일상복으로서의 불편함을 개선하고 현대적 감각을 더한 생활한복 혹은 모던한복으로 재해석되며 새로운 변신을 꾀하고 있다. 전통 문양과 깃, 고름 등 고유의 디테일은 살리되 신축성 있는 소재와 단순화된 디자인을 적용하여 대중성을 확보했다. 특히 세계적인 K-Pop 스타들이 무대 의상으로 한복을 입고 등장하면서 전 세계 젊은 세대 사이에서 독창적인 패션 아이템으로 각광받기 시작했다. 이와 같은 한복의 현대적 변신은 전통문화의 보존이 과거에 머무르는 것이 아니라, 현대 사회와의 끊임없는 소통을 통해 생명력을 얻는 과정임을 잘 보여준다.',
    'Hanbok adalah pakaian tradisional yang telah mendampingi orang Korea sepanjang sejarah panjang dan merangkum nilai budaya serta kesadaran estetika zaman tersebut. Secara mendasar, hanbok memiliki atasan dan bawahan terpisah dengan mobilitas tinggi, serta menghasilkan aliran garis alami saat dikenakan dengan pemotongan pola datar. Di era modern, hanbok ditafsirkan ulang sebagai saenghwal hanbok (hanbok sehari-hari) yang memperbaiki ketidaknyamanan pakaian tradisional dan menambahkan kepekaan modern. Detail khas dipertahankan, namun popularitas diperoleh dengan bahan elastis dan desain yang disederhanakan. Seiring bintang K-Pop global tampil mengenakan hanbok, pakaian ini mulai mendapat perhatian sebagai item mode unik di seluruh dunia. Transformasi modern hanbok menunjukkan bahwa pelestarian budaya tradisional memperoleh vitalitas melalui komunikasi dengan masyarakat modern.',
    'Hanbok is a traditional costume that has accompanied Koreans throughout a long history, containing cultural values and aesthetic sensibilities. It is structured with separate top and bottom garments, providing excellent mobility, and creates natural flowing lines when worn using flat tailoring. In modern times, hanbok is undergoing a transformation, reinterpreted as saenghwal hanbok (casual hanbok) to improve the inconvenience of daily wear and add modern sensibilities. Unique details like traditional patterns are preserved, while popularity is secured by flexible materials and simplified designs. As K-Pop stars wore hanbok, it began to gain limelight as a fashion item worldwide. Such modern transformation of hanbok demonstrates that preserving traditional culture is a process of gaining vitality through constant communication.',
    'advanced',
    'k_culture',
    'https://images.unsplash.com/photo-1548115184-bc6544d06a58?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "한복은", "l": "한복"},
  {"t": " ", "l": " "},
  {"t": "오랜", "l": "오래"},
  {"t": " ", "l": " "},
  {"t": "역사", "l": "역사"},
  {"t": " ", "l": " "},
  {"t": "동안", "l": "동안"},
  {"t": " ", "l": " "},
  {"t": "한국인과", "l": "한국인"},
  {"t": " ", "l": " "},
  {"t": "함께하며", "l": "함께하다"},
  {"t": " ", "l": " "},
  {"t": "시대의", "l": "시대"},
  {"t": " ", "l": " "},
  {"t": "문화적", "l": "문화적"},
  {"t": " ", "l": " "},
  {"t": "가치와", "l": "가치"},
  {"t": " ", "l": " "},
  {"t": "미의식을", "l": "미의식"},
  {"t": " ", "l": " "},
  {"t": "담아온", "l": "담다"},
  {"t": " ", "l": " "},
  {"t": "전통", "l": "전통"},
  {"t": " ", "l": " "},
  {"t": "복식이다", "l": "복식"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "기본적으로", "l": "기본적으로"},
  {"t": " ", "l": " "},
  {"t": "상의와", "l": "상의"},
  {"t": " ", "l": " "},
  {"t": "하의가", "l": "하의"},
  {"t": " ", "l": " "},
  {"t": "분리된", "l": "분리되다"},
  {"t": " ", "l": " "},
  {"t": "구조로", "l": "구조"},
  {"t": " ", "l": " "},
  {"t": "되어", "l": "되다"},
  {"t": " ", "l": " "},
  {"t": "있어", "l": "있다"},
  {"t": " ", "l": " "},
  {"t": "활동성이", "l": "활동성"},
  {"t": " ", "l": " "},
  {"t": "뛰어나며", "l": "뛰어나다"},
  {"t": " ", "l": " "},
  {"t": "평면", "l": "평면"},
  {"t": " ", "l": " "},
  {"t": "재단법을", "l": "재단법"},
  {"t": " ", "l": " "},
  {"t": "사용하여", "l": "사용하다"},
  {"t": " ", "l": " "},
  {"t": "입었을", "l": "입다"},
  {"t": " ", "l": " "},
  {"t": "때", "l": "때"},
  {"t": " ", "l": " "},
  {"t": "자연스러운", "l": "자연스럽다"},
  {"t": " ", "l": " "},
  {"t": "선의", "l": "선"},
  {"t": " ", "l": " "},
  {"t": "흐름과", "l": "흐름"},
  {"t": " ", "l": " "},
  {"t": "여유로운", "l": "여유롭다"},
  {"t": " ", "l": " "},
  {"t": "실루엣을", "l": "실루엣"},
  {"t": " ", "l": " "},
  {"t": "만들어내는", "l": "만들어내다"},
  {"t": " ", "l": " "},
  {"t": "것이", "l": "것"},
  {"t": " ", "l": " "},
  {"t": "특징이다", "l": "특징"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "전통", "l": "전통"},
  {"t": " ", "l": " "},
  {"t": "한복의", "l": "한복"},
  {"t": " ", "l": " "},
  {"t": "색채는", "l": "색채"},
  {"t": " ", "l": " "},
  {"t": "음양오행", "l": "음양오행"},
  {"t": " ", "l": " "},
  {"t": "사상에", "l": "사상"},
  {"t": " ", "l": " "},
  {"t": "기반한", "l": "기반하다"},
  {"t": " ", "l": " "},
  {"t": "오방색을", "l": "오방색"},
  {"t": " ", "l": " "},
  {"t": "주로", "l": "주로"},
  {"t": " ", "l": " "},
  {"t": "사용하여", "l": "사용하다"},
  {"t": " ", "l": " "},
  {"t": "자연과의", "l": "자연"},
  {"t": " ", "l": " "},
  {"t": "조화를", "l": "조화"},
  {"t": " ", "l": " "},
  {"t": "지향했다", "l": "지향하다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "현대에", "l": "현대"},
  {"t": " ", "l": " "},
  {"t": "이르러", "l": "이르다"},
  {"t": " ", "l": " "},
  {"t": "한복은", "l": "한복"},
  {"t": " ", "l": " "},
  {"t": "일상복으로서의", "l": "일상복"},
  {"t": " ", "l": " "},
  {"t": "불편함을", "l": "불편함"},
  {"t": " ", "l": " "},
  {"t": "개선하고", "l": "개선하다"},
  {"t": " ", "l": " "},
  {"t": "현대적", "l": "현대적"},
  {"t": " ", "l": " "},
  {"t": "감각을", "l": "감각"},
  {"t": " ", "l": " "},
  {"t": "더한", "l": "보다"},
  {"t": " ", "l": " "},
  {"t": "생활한복", "l": "생활한복"},
  {"t": " ", "l": " "},
  {"t": "혹은", "l": "혹은"},
  {"t": " ", "l": " "},
  {"t": "모던한복으로", "l": "모던한복"},
  {"t": " ", "l": " "},
  {"t": "재해석되며", "l": "재해석되다"},
  {"t": " ", "l": " "},
  {"t": "새로운", "l": "새롭다"},
  {"t": " ", "l": " "},
  {"t": "변신을", "l": "변신"},
  {"t": " ", "l": " "},
  {"t": "꾀하고", "l": "꾀하다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "전통", "l": "전통"},
  {"t": " ", "l": " "},
  {"t": "문양과", "l": "문양"},
  {"t": " ", "l": " "},
  {"t": "깃", "l": "깃"},
  {"t": " ", "l": " "},
  {"t": "고름", "l": "고름"},
  {"t": " ", "l": " "},
  {"t": "등", "l": "등"},
  {"t": " ", "l": " "},
  {"t": "고유의", "l": "고유"},
  {"t": " ", "l": " "},
  {"t": "디테일은", "l": "디테일"},
  {"t": " ", "l": " "},
  {"t": "살리되", "l": "살리다"},
  {"t": " ", "l": " "},
  {"t": "신축성", "l": "신축성"},
  {"t": " ", "l": " "},
  {"t": "있는", "l": "있다"},
  {"t": " ", "l": " "},
  {"t": "소재와", "l": "소재"},
  {"t": " ", "l": " "},
  {"t": "단순화된", "l": "단순화되다"},
  {"t": " ", "l": " "},
  {"t": "디자인을", "l": "디자인"},
  {"t": " ", "l": " "},
  {"t": "적용하여", "l": "적용하다"},
  {"t": " ", "l": " "},
  {"t": "대중성을", "l": "대중성"},
  {"t": " ", "l": " "},
  {"t": "확보했다", "l": "확보하다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "특히", "l": "특히"},
  {"t": " ", "l": " "},
  {"t": "세계적인", "l": "세계적"},
  {"t": " ", "l": " "},
  {"t": "K-Pop", "l": "K-Pop"},
  {"t": " ", "l": " "},
  {"t": "스타들이", "l": "스타"},
  {"t": " ", "l": " "},
  {"t": "무대", "l": "무대"},
  {"t": " ", "l": " "},
  {"t": "의상으로", "l": "의상"},
  {"t": " ", "l": " "},
  {"t": "한복을", "l": "한복"},
  {"t": " ", "l": " "},
  {"t": "입고", "l": "입다"},
  {"t": " ", "l": " "},
  {"t": "등장하면서", "l": "등장하다"},
  {"t": " ", "l": " "},
  {"t": "전", "l": "전"},
  {"t": " ", "l": " "},
  {"t": "세계", "l": "세계"},
  {"t": " ", "l": " "},
  {"t": "젊은", "l": "젊다"},
  {"t": " ", "l": " "},
  {"t": "세대", "l": "세대"},
  {"t": " ", "l": " "},
  {"t": "사이에서", "l": "사이"},
  {"t": " ", "l": " "},
  {"t": "독창적인", "l": "독창적"},
  {"t": " ", "l": " "},
  {"t": "패션", "l": "패션"},
  {"t": " ", "l": " "},
  {"t": "아이템으로", "l": "아이템"},
  {"t": " ", "l": " "},
  {"t": "각광받기", "l": "각광받다"},
  {"t": " ", "l": " "},
  {"t": "시작했다", "l": "시작하다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "이와", "l": "이"},
  {"t": " ", "l": " "},
  {"t": "같은", "l": "같다"},
  {"t": " ", "l": " "},
  {"t": "한복의", "l": "한복"},
  {"t": " ", "l": " "},
  {"t": "현대적", "l": "현대적"},
  {"t": " ", "l": " "},
  {"t": "변신은", "l": "변신"},
  {"t": " ", "l": " "},
  {"t": "전통문화의", "l": "전통문화"},
  {"t": " ", "l": " "},
  {"t": "보존이", "l": "보존"},
  {"t": " ", "l": " "},
  {"t": "과거에", "l": "과거"},
  {"t": " ", "l": " "},
  {"t": "머무르는", "l": "머무르다"},
  {"t": " ", "l": " "},
  {"t": "것이", "l": "것"},
  {"t": " ", "l": " "},
  {"t": "아니라", "l": "아니다"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "현대", "l": "현대"},
  {"t": " ", "l": " "},
  {"t": "사회와의", "l": "사회"},
  {"t": " ", "l": " "},
  {"t": "끊임없는", "l": "끊임없다"},
  {"t": " ", "l": " "},
  {"t": "소통을", "l": "소통"},
  {"t": " ", "l": " "},
  {"t": "통해", "l": "통하다"},
  {"t": " ", "l": " "},
  {"t": "생명력을", "l": "생명력"},
  {"t": " ", "l": " "},
  {"t": "얻는", "l": "얻다"},
  {"t": " ", "l": " "},
  {"t": "과정임을", "l": "과정"},
  {"t": " ", "l": " "},
  {"t": "잘", "l": "잘"},
  {"t": " ", "l": " "},
  {"t": "보여준다", "l": "보여주다"},
  {"t": ".", "l": "."}
]'::jsonb
);