-- Migration: 013_add_more_stories_part2.sql
-- Description: Add another 3 intermediate and 3 advanced stories with interactive word tokens

INSERT INTO public.stories (
    title_ko,
    title_id,
    title_en,
    content_ko,
    content_id,
    content_en,
    level,
    category,
    cover_image_url,
    is_published,
    content_tokens
) VALUES
(
    '한국의 한글날',
    'Hari Hangul di Korea',
    'Hangul Day in Korea',
    '한글날은 한글을 만든 세종대왕의 공적을 기리고 한글의 우수성을 널리 알리기 위한 한국의 국경일이에요. 매년 10월 9일로 지정되어 있으며, 공휴일이라서 직장인들과 학생들이 쉬어요. 한글은 조선 시대 세종대왕이 백성들이 쉽게 글을 읽고 쓸 수 있도록 만들기 위해 창제한 과학적인 글자예요. 한글날에는 전국에서 다양한 한글 관련 축제와 행사들이 열려요. 많은 한국인들이 이 날을 통해 우리글의 아름다움과 소중함을 다시 한번 생각해요.',
    'Hari Hangul adalah hari nasional Korea untuk memperingati jasa Raja Sejong yang menciptakan Hangul dan menyebarluaskan keunggulan Hangul. Hari ini ditetapkan pada tanggal 9 Oktober setiap tahunnya, dan karena merupakan hari libur nasional, pekerja kantoran dan pelajar berlibur. Hangul adalah huruf ilmiah yang diciptakan oleh Raja Sejong pada masa Dinasti Joseon agar rakyat dapat membaca dan menulis dengan mudah. Pada Hari Hangul, berbagai festival dan acara terkait Hangul diadakan di seluruh negeri. Banyak orang Korea yang memikirkan kembali keindahan dan pentingnya tulisan kita melalui hari ini.',
    'Hangul Day is a Korean national holiday to commemorate the achievements of King Sejong, who created Hangul, and to widely promote the excellence of Hangul. It is designated on October 9 every year, and because it is a public holiday, workers and students take a rest. Hangul is a scientific character created by King Sejong during the Joseon Dynasty to make it easy for the people to read and write. On Hangul Day, various Hangul-related festivals and events are held nationwide. Many Koreans think again about the beauty and value of our writing through this day.',
    'intermediate',
    'k_culture',
    'https://images.unsplash.com/photo-1617839625591-e5a789593135?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "한글날은", "l": "한글날"},
  {"t": " ", "l": " "},
  {"t": "한글을", "l": "한글"},
  {"t": " ", "l": " "},
  {"t": "만든", "l": "만들다"},
  {"t": " ", "l": " "},
  {"t": "세종대왕의", "l": "세종대왕"},
  {"t": " ", "l": " "},
  {"t": "공적을", "l": "공적"},
  {"t": " ", "l": " "},
  {"t": "기리고", "l": "기리다"},
  {"t": " ", "l": " "},
  {"t": "한글의", "l": "한글"},
  {"t": " ", "l": " "},
  {"t": "우수성을", "l": "우수성"},
  {"t": " ", "l": " "},
  {"t": "널리", "l": "널리"},
  {"t": " ", "l": " "},
  {"t": "알리기", "l": "알리다"},
  {"t": " ", "l": " "},
  {"t": "위한", "l": "위하다"},
  {"t": " ", "l": " "},
  {"t": "한국의", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "국경일이에요", "l": "국경일"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "매년", "l": "매년"},
  {"t": " ", "l": " "},
  {"t": "10월", "l": "10월"},
  {"t": " ", "l": " "},
  {"t": "9일로", "l": "9일"},
  {"t": " ", "l": " "},
  {"t": "지정되어", "l": "지정되다"},
  {"t": " ", "l": " "},
  {"t": "있으며", "l": "있다"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "공휴일이라서", "l": "공휴일"},
  {"t": " ", "l": " "},
  {"t": "직장인들과", "l": "직장인"},
  {"t": " ", "l": " "},
  {"t": "학생들이", "l": "학생"},
  {"t": " ", "l": " "},
  {"t": "쉬어요", "l": "쉬다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "한글은", "l": "한글"},
  {"t": " ", "l": " "},
  {"t": "조선", "l": "조선"},
  {"t": " ", "l": " "},
  {"t": "시대", "l": "시대"},
  {"t": " ", "l": " "},
  {"t": "세종대왕이", "l": "세종대왕"},
  {"t": " ", "l": " "},
  {"t": "백성들이", "l": "백성"},
  {"t": " ", "l": " "},
  {"t": "쉽게", "l": "쉽게"},
  {"t": " ", "l": " "},
  {"t": "글을", "l": "글"},
  {"t": " ", "l": " "},
  {"t": "읽고", "l": "읽다"},
  {"t": " ", "l": " "},
  {"t": "쓸", "l": "쓰다"},
  {"t": " ", "l": " "},
  {"t": "수", "l": "수"},
  {"t": " ", "l": " "},
  {"t": "있도록", "l": "있다"},
  {"t": " ", "l": " "},
  {"t": "만들기", "l": "만들다"},
  {"t": " ", "l": " "},
  {"t": "위해", "l": "위하다"},
  {"t": " ", "l": " "},
  {"t": "창제한", "l": "창제하다"},
  {"t": " ", "l": " "},
  {"t": "과학적인", "l": "과학적"},
  {"t": " ", "l": " "},
  {"t": "글자예요", "l": "글자"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "한글날에는", "l": "한글날"},
  {"t": " ", "l": " "},
  {"t": "전국에서", "l": "전국"},
  {"t": " ", "l": " "},
  {"t": "다양한", "l": "다양하다"},
  {"t": " ", "l": " "},
  {"t": "한글", "l": "한글"},
  {"t": " ", "l": " "},
  {"t": "관련", "l": "관련"},
  {"t": " ", "l": " "},
  {"t": "축제와", "l": "축제"},
  {"t": " ", "l": " "},
  {"t": "행사들이", "l": "행사"},
  {"t": " ", "l": " "},
  {"t": "열려요", "l": "열리다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "많은", "l": "많다"},
  {"t": " ", "l": " "},
  {"t": "한국인들이", "l": "한국인"},
  {"t": " ", "l": " "},
  {"t": "이", "l": "이"},
  {"t": " ", "l": " "},
  {"t": "날을", "l": "날"},
  {"t": " ", "l": " "},
  {"t": "통해", "l": "통하다"},
  {"t": " ", "l": " "},
  {"t": "우리글의", "l": "우리글"},
  {"t": " ", "l": " "},
  {"t": "아름다움과", "l": "아름다움"},
  {"t": " ", "l": " "},
  {"t": "소중함을", "l": "소중함"},
  {"t": " ", "l": " "},
  {"t": "다시", "l": "다시"},
  {"t": " ", "l": " "},
  {"t": "한번", "l": "한번"},
  {"t": " ", "l": " "},
  {"t": "생각해요", "l": "생각하다"},
  {"t": ".", "l": "."}
]'::jsonb
),
(
    '제주도 여행',
    'Wisata Pulau Jeju',
    'Traveling to Jeju Island',
    '제주도는 한국에서 가장 크고 유명한 관광 섬이에요. 아름다운 바다와 깨끗한 자연이 있어서 일 년 내내 많은 관광객들이 방문해요. 제주도의 중심에는 남한에서 가장 높은 한라산이 솟아 있어요. 봄에는 노란 유채꽃이 만발하고, 가을에는 억새가 바람에 흔들려 멋진 풍경을 보여 줘요. 제주도의 대표적인 특산물은 달콤한 귤과 신선한 해산물이에요. 한라산을 등산하거나 해안 도로를 따라 드라이브를 하는 코스가 특히 인기가 많아요.',
    'Pulau Jeju adalah pulau wisata terbesar dan paling terkenal di Korea. Karena memiliki laut yang indah dan alam yang bersih, banyak wisatawan berkunjung sepanjang tahun. Di tengah Pulau Jeju menjulang Gunung Halla yang merupakan gunung tertinggi di Korea Selatan. Pada musim semi, bunga kanola kuning bermekaran penuh, dan pada musim gugur, rumput alang-alang bergoyang tertiup angin menampilkan pemandangan yang indah. Produk khas Pulau Jeju adalah jeruk manis dan makanan laut segar. Rute mendaki Gunung Halla atau berkendara menyusuri jalan pantai sangat populer.',
    'Jeju Island is the largest and most famous tourist island in Korea. With its beautiful sea and clean nature, many tourists visit throughout the year. In the center of Jeju Island rises Mount Halla, the highest mountain in South Korea. In spring, yellow canola flowers bloom fully, and in autumn, silver grass sways in the wind, showing wonderful scenery. The representative specialties of Jeju Island are sweet tangerines and fresh seafood. Hiking Mount Halla or driving along the coastal road is particularly popular.',
    'intermediate',
    'travel',
    'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "제주도는", "l": "제주도"},
  {"t": " ", "l": " "},
  {"t": "한국에서", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "가장", "l": "가장"},
  {"t": " ", "l": " "},
  {"t": "크고", "l": "크다"},
  {"t": " ", "l": " "},
  {"t": "유명한", "l": "유명하다"},
  {"t": " ", "l": " "},
  {"t": "관광", "l": "관광"},
  {"t": " ", "l": " "},
  {"t": "섬이에요", "l": "섬이다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "아름다운", "l": "아름답다"},
  {"t": " ", "l": " "},
  {"t": "바다와", "l": "바다"},
  {"t": " ", "l": " "},
  {"t": "깨끗한", "l": "깨끗하다"},
  {"t": " ", "l": " "},
  {"t": "자연이", "l": "자연"},
  {"t": " ", "l": " "},
  {"t": "있어서", "l": "있다"},
  {"t": " ", "l": " "},
  {"t": "일", "l": "일"},
  {"t": " ", "l": " "},
  {"t": "년", "l": "년"},
  {"t": " ", "l": " "},
  {"t": "내내", "l": "내내"},
  {"t": " ", "l": " "},
  {"t": "많은", "l": "많다"},
  {"t": " ", "l": " "},
  {"t": "관광객들이", "l": "관광객"},
  {"t": " ", "l": " "},
  {"t": "방문해요", "l": "방문하다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "제주도의", "l": "제주도"},
  {"t": " ", "l": " "},
  {"t": "중심에는", "l": "중심"},
  {"t": " ", "l": " "},
  {"t": "남한에서", "l": "남한"},
  {"t": " ", "l": " "},
  {"t": "가장", "l": "가장"},
  {"t": " ", "l": " "},
  {"t": "높은", "l": "높다"},
  {"t": " ", "l": " "},
  {"t": "한라산이", "l": "한라산"},
  {"t": " ", "l": " "},
  {"t": "솟아", "l": "솟다"},
  {"t": " ", "l": " "},
  {"t": "있어요", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "봄에는", "l": "봄"},
  {"t": " ", "l": " "},
  {"t": "노란", "l": "노랗다"},
  {"t": " ", "l": " "},
  {"t": "유채꽃이", "l": "유채꽃"},
  {"t": " ", "l": " "},
  {"t": "만발하고", "l": "만발하다"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "가을에는", "l": "가을"},
  {"t": " ", "l": " "},
  {"t": "억새가", "l": "억새"},
  {"t": " ", "l": " "},
  {"t": "바람에", "l": "바람"},
  {"t": " ", "l": " "},
  {"t": "흔들려", "l": "흔들리다"},
  {"t": " ", "l": " "},
  {"t": "멋진", "l": "멋지다"},
  {"t": " ", "l": " "},
  {"t": "풍경을", "l": "풍경"},
  {"t": " ", "l": " "},
  {"t": "보여", "l": "보이다"},
  {"t": " ", "l": " "},
  {"t": "줘요", "l": "주다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "제주도의", "l": "제주도"},
  {"t": " ", "l": " "},
  {"t": "대표적인", "l": "대표적이다"},
  {"t": " ", "l": " "},
  {"t": "특산물은", "l": "특산물"},
  {"t": " ", "l": " "},
  {"t": "달콤한", "l": "달콤하다"},
  {"t": " ", "l": " "},
  {"t": "귤과", "l": "귤"},
  {"t": " ", "l": " "},
  {"t": "신선한", "l": "신선하다"},
  {"t": " ", "l": " "},
  {"t": "해산물이에요", "l": "해산물이다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "한라산을", "l": "한라산"},
  {"t": " ", "l": " "},
  {"t": "등산하거나", "l": "등산하다"},
  {"t": " ", "l": " "},
  {"t": "해안", "l": "해안"},
  {"t": " ", "l": " "},
  {"t": "도로를", "l": "도로"},
  {"t": " ", "l": " "},
  {"t": "따라", "l": "따르다"},
  {"t": " ", "l": " "},
  {"t": "드라이브를", "l": "드라이브"},
  {"t": " ", "l": " "},
  {"t": "하는", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "코스가", "l": "코스"},
  {"t": " ", "l": " "},
  {"t": "특히", "l": "특히"},
  {"t": " ", "l": " "},
  {"t": "인기가", "l": "인기"},
  {"t": " ", "l": " "},
  {"t": "많아요", "l": "많다"},
  {"t": ".", "l": "."}
]'::jsonb
),
(
    '한국의 카페 문화',
    'Budaya Kafe di Korea',
    'Cafe Culture in Korea',
    '한국에는 길거리마다 카페가 아주 많이 있어요. 한국 사람들은 밥을 먹은 후에 커피를 마시는 습관이 있어요. 특히 얼음을 넣은 아메리카노, 즉 ''아아''는 가장 인기가 많은 메뉴예요. 카페는 단순히 커피를 마시는 곳이 아니라 친구와 수다를 떨거나 혼자 공부를 하는 공간이기도 해요. 최근에는 공부나 업무를 하는 사람들을 위한 ''카공족''이라는 말도 생겼어요. 이색적인 인테리어의 예쁜 카페나 다양한 디저트를 파는 카페를 찾아다니는 것도 젊은이들의 인기 있는 취미예요.',
    'Di Korea, ada banyak sekali kafe di setiap jalan. Orang Korea memiliki kebiasaan meminum kopi setelah makan. Khususnya, Americano dengan es batu yang disebut ''Ah-Ah'' (Ice Americano) adalah menu paling populer. Kafe bukan sekadar tempat meminum kopi, melainkan juga ruang untuk mengobrol bersama teman atau belajar sendiri. Baru-baru ini, istilah ''Kagongjok'' (orang yang belajar di kafe) juga muncul untuk orang yang belajar atau bekerja. Mencari kafe cantik dengan interior unik atau kafe yang menjual berbagai makanan penutup juga merupakan hobi yang populer di kalangan anak muda.',
    'In Korea, there are many cafes on every street. Korean people have a habit of drinking coffee after eating. In particular, iced Americano, known as ''Ah-Ah'', is the most popular menu item. A cafe is not simply a place to drink coffee, but also a space to chat with friends or study alone. Recently, the term ''Kagongjok'' (cafe-study group) was coined for people who study or work in cafes. Searching for pretty cafes with unique interiors or cafes that sell various desserts is also a popular hobby among young people.',
    'intermediate',
    'daily_life',
    'https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "한국", "l": "한국"},
  {"t": "에는", "l": "이다"},
  {"t": " ", "t": " "},
  {"t": "길거리", "l": "길거리"},
  {"t": "마다", "l": "마다"},
  {"t": " ", "t": " "},
  {"t": "카페", "l": "카페"},
  {"t": "가", "l": "이다"},
  {"t": " ", "t": " "},
  {"t": "아주", "l": "아주"},
  {"t": " ", "t": " "},
  {"t": "많이", "l": "많다"},
  {"t": " ", "t": " "},
  {"t": "있어요", "l": "있다"},
  {"t": ".", "t": "."},
  {"t": "\n", "t": "\n"},
  {"t": "한국", "l": "한국"},
  {"t": " ", "t": " "},
  {"t": "사람들", "l": "사람"},
  {"t": "은", "l": "이다"},
  {"t": " ", "t": " "},
  {"t": "밥", "l": "밥"},
  {"t": "을", "l": "을"},
  {"t": " ", "t": " "},
  {"t": "먹은", "l": "먹다"},
  {"t": " ", "t": " "},
  {"t": "후에", "l": "후"},
  {"t": " ", "t": " "},
  {"t": "커피", "l": "커피"},
  {"t": "를", "l": "를"},
  {"t": " ", "t": " "},
  {"t": "마시는", "l": "마시다"},
  {"t": " ", "t": " "},
  {"t": "습관", "l": "습관"},
  {"t": "이", "l": "이다"},
  {"t": " ", "t": " "},
  {"t": "있어요", "l": "있다"},
  {"t": ".", "t": "."},
  {"t": "\n", "t": "\n"},
  {"t": "특히", "l": "특히"},
  {"t": " ", "t": " "},
  {"t": "얼음", "l": "얼음"},
  {"t": "을", "l": "를"},
  {"t": " ", "t": " "},
  {"t": "넣은", "l": "넣다"},
  {"t": " ", "t": " "},
  {"t": "아메리카노", "l": "아메리카노"},
  {"t": ",", "t": ","},
  {"t": " ", "t": " "},
  {"t": "즉", "l": "즉"},
  {"t": "''", "t": "''"},
  {"t": "아아", "l": "아아"},
  {"t": "''", "t": "''"},
  {"t": "는", "l": "이다"},
  {"t": " ", "t": " "},
  {"t": "가장", "l": "가장"},
  {"t": " ", "t": " "},
  {"t": "인기", "l": "인기"},
  {"t": "가", "l": "이다"},
  {"t": " ", "t": " "},
  {"t": "많은", "l": "많다"},
  {"t": " ", "t": " "},
  {"t": "메뉴", "l": "메뉴"},
  {"t": "예요", "l": "이다"},
  {"t": ".", "t": "."},
  {"t": "\n", "t": "\n"},
  {"t": "카페", "l": "카페"},
  {"t": "는", "l": "이다"},
  {"t": " ", "t": " "},
  {"t": "단순히", "l": "단순히"},
  {"t": " ", "t": " "},
  {"t": "커피", "l": "커피"},
  {"t": "를", "l": "를"},
  {"t": " ", "t": " "},
  {"t": "마시는", "l": "마시다"},
  {"t": " ", "t": " "},
  {"t": "곳", "l": "곳"},
  {"t": "이", "l": "이다"},
  {"t": " ", "t": " "},
  {"t": "아니라", "l": "아니다"},
  {"t": " ", "t": " "},
  {"t": "친구", "l": "친구"},
  {"t": "와", "l": "와"},
  {"t": " ", "t": " "},
  {"t": "수다", "l": "수다"},
  {"t": "를", "l": "를"},
  {"t": " ", "t": " "},
  {"t": "떨거나", "l": "떨다"},
  {"t": " ", "t": " "},
  {"t": "혼자", "l": "혼자"},
  {"t": " ", "t": " "},
  {"t": "공부", "l": "공부"},
  {"t": "를", "l": "를"},
  {"t": " ", "t": " "},
  {"t": "하는", "l": "하다"},
  {"t": " ", "t": " "},
  {"t": "공간", "l": "공간"},
  {"t": "이", "l": "이다"},
  {"t": "기도", "l": "이다"},
  {"t": " ", "t": " "},
  {"t": "해요", "l": "하다"},
  {"t": ".", "t": "."},
  {"t": "\n", "t": "\n"},
  {"t": "최근", "l": "최근"},
  {"t": "에는", "l": "이다"},
  {"t": " ", "t": " "},
  {"t": "공부", "l": "공부"},
  {"t": "나", "l": "나"},
  {"t": " ", "t": " "},
  {"t": "업무", "l": "업무"},
  {"t": "를", "l": "를"},
  {"t": " ", "t": " "},
  {"t": "하는", "l": "하다"},
  {"t": " ", "t": " "},
  {"t": "사람들", "l": "사람"},
  {"t": "을", "l": "을"},
  {"t": " ", "t": " "},
  {"t": "위한", "l": "위하다"},
  {"t": " ", "t": " "},
  {"t": "''", "t": "''"},
  {"t": "카공족", "l": "카공족"},
  {"t": "''", "t": "''"},
  {"t": "이라는", "l": "이다"},
  {"t": " ", "t": " "},
  {"t": "말", "l": "말"},
  {"t": "도", "l": "도"},
  {"t": " ", "t": " "},
  {"t": "생겼어요", "l": "생기다"},
  {"t": ".", "t": "."},
  {"t": "\n", "t": "\n"},
  {"t": "이색적인", "l": "이색적이다"},
  {"t": " ", "t": " "},
  {"t": "인테리어", "l": "인테리어"},
  {"t": "의", "l": "의"},
  {"t": " ", "t": " "},
  {"t": "예쁜", "l": "예쁘다"},
  {"t": " ", "t": " "},
  {"t": "카페", "l": "카페"},
  {"t": "나", "l": "나"},
  {"t": " ", "t": " "},
  {"t": "다양한", "l": "다양하다"},
  {"t": " ", "t": " "},
  {"t": "디저트", "l": "디저트"},
  {"t": "를", "l": "를"},
  {"t": " ", "t": " "},
  {"t": "파는", "l": "팔다"},
  {"t": " ", "t": " "},
  {"t": "카페", "l": "카페"},
  {"t": "를", "l": "를"},
  {"t": " ", "t": " "},
  {"t": "찾아다니는", "l": "찾아다니다"},
  {"t": " ", "t": " "},
  {"t": "것", "l": "것"},
  {"t": "도", "l": "도"},
  {"t": " ", "t": " "},
  {"t": "젊은이", "l": "젊은이"},
  {"t": "들", "l": "들"},
  {"t": "의", "l": "의"},
  {"t": " ", "t": " "},
  {"t": "인기", "l": "인기"},
  {"t": " ", "t": " "},
  {"t": "있는", "l": "있다"},
  {"t": " ", "t": " "},
  {"t": "취미", "l": "취미"},
  {"t": "예요", "l": "이다"},
  {"t": ".", "t": "."}
]'::jsonb
),
(
    '한국의 고령화 사회',
    'Masyarakat Lanjut Usia di Korea',
    'Korea''s Aging Society',
    '한국 사회는 세계에서 유례를 찾아보기 힘들 정도로 빠르게 초고령 사회로 진입하고 있다. 평균 수명의 연장과 극심한 저출산 현상이 결합하면서 전체 인구 중 고령층이 차지하는 비율이 급증하는 추세다. 이러한 인구 통계학적 변화는 노동력 부족, 잠재성장률 하락, 그리고 사회보장 비용의 폭증이라는 다각적인 경제적 문제를 야기하고 있다. 특히 국민연금의 재정 고갈 우려와 건강보험 재정 압박은 노후 소득 보장과 의료 복지 제도의 지속 가능성에 의문을 제기하게 만든다. 또한, 노인 빈곤율과 고독사 문제가 심각한 사회적 화두로 떠오르고 있다. 기성세대의 은퇴 후 소득 단절과 핵가족화로 인한 정서적 고립은 전통적인 가족 공동체의 부양 기능을 약화시켰다. 이를 해결하기 위해 정부는 노인 일자리 창출, 지역사회 통합 돌봄 서비스 구축 등 노인 복지 정책을 다변화하고 있다. 지속 가능한 초고령 사회를 구축하기 위해서는 단순한 복지 수혜 대상으로서의 노인 지원을 넘어, 고령 인구가 생산적인 사회 활동을 지속할 수 있는 근로 환경 개선과 사회적 인식의 대전환이 병행되어야 한다.',
    'Masyarakat Korea sedang memasuki masyarakat super-tua (super-aged society) dengan kecepatan yang sulit ditemukan padanannya di dunia. Kombinasi dari perpanjangan harapan hidup rata-rata dan fenomena angka kelahiran yang sangat rendah menyebabkan proporsi populasi lanjut usia dalam populasi total melonjak dengan cepat. Perubahan demografis ini menimbulkan masalah ekonomi multidimensi seperti kekurangan tenaga kerja, penurunan potensi pertumbuhan, dan ledakan biaya jaminan sosial. Khususnya, kekhawatiran tentang habisnya dana pensiun nasional dan tekanan pada keuangan asuransi kesehatan menimbulkan keraguan atas keberlanjutan jaminan pendapatan hari tua dan sistem kesejahteraan medis. Selain itu, masalah tingkat kemiskinan lansia dan kematian dalam kesendirian (lonely death/godoksa) muncul sebagai topik sosial yang serius. Terputusnya pendapatan generasi tua setelah pensiun dan isolasi emosional akibat tren keluarga inti telah melemahkan fungsi pendukung komunitas keluarga tradisional. Untuk mengatasi hal ini, pemerintah mendiversifikasi kebijakan kesejahteraan lansia seperti penciptaan lapangan kerja lansia dan pembangunan layanan perawatan terintegrasi masyarakat. Untuk membangun masyarakat super-tua yang berkelanjutan, peningkatan lingkungan kerja agar populasi lanjut usia dapat melanjutkan kegiatan sosial yang produktif serta transformasi besar dalam persepsi sosial harus dilakukan secara paralel.',
    'Korean society is entering a super-aged society at an unprecedented speed. The combination of extended average life expectancy and extreme low birth rates is causing the proportion of the elderly population in the total population to surge. This demographic change is causing multifaceted economic issues such as labor shortages, declining potential growth, and exploding social security costs. In particular, concerns over the depletion of the national pension and pressure on health insurance finance raise questions about the sustainability of old-age income security and medical welfare systems. Furthermore, the issues of elderly poverty and lonely deaths (godoksa) are emerging as serious social topics. The disconnection of income after retirement for the older generation and emotional isolation caused by nuclearization have weakened the supportive functions of traditional family communities. To resolve this, the government is diversifying elderly welfare policies, including creating jobs for the elderly and building community-integrated care services. To build a sustainable super-aged society, improving the working environment so that the older population can continue productive social activities and a major shift in social perception must be pursued in parallel.',
    'advanced',
    'society',
    'https://images.unsplash.com/photo-1473186578172-c141e6798cf4?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "한국", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "사회는", "l": "사회"},
  {"t": " ", "l": " "},
  {"t": "세계에서", "l": "세계"},
  {"t": " ", "l": " "},
  {"t": "유례를", "l": "유례"},
  {"t": " ", "l": " "},
  {"t": "찾아보기", "l": "찾아보다"},
  {"t": " ", "l": " "},
  {"t": "힘들", "l": "힘들다"},
  {"t": " ", "l": " "},
  {"t": "정도로", "l": "정도"},
  {"t": " ", "l": " "},
  {"t": "빠르게", "l": "빠르다"},
  {"t": " ", "l": " "},
  {"t": "초고령", "l": "초고령"},
  {"t": " ", "l": " "},
  {"t": "사회로", "l": "사회"},
  {"t": " ", "l": " "},
  {"t": "진입하고", "l": "진입하다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "평균", "l": "평균"},
  {"t": " ", "l": " "},
  {"t": "수명의", "l": "수명"},
  {"t": " ", "l": " "},
  {"t": "연장과", "l": "연장"},
  {"t": " ", "l": " "},
  {"t": "극심한", "l": "극심하다"},
  {"t": " ", "l": " "},
  {"t": "저출산", "l": "저출산"},
  {"t": " ", "l": " "},
  {"t": "현상이", "l": "현상"},
  {"t": " ", "l": " "},
  {"t": "결합하면서", "l": "결합하다"},
  {"t": " ", "l": " "},
  {"t": "전체", "l": "전체"},
  {"t": " ", "l": " "},
  {"t": "인구", "l": "인구"},
  {"t": " ", "l": " "},
  {"t": "중", "l": "중"},
  {"t": " ", "l": " "},
  {"t": "고령층이", "l": "고령층"},
  {"t": " ", "l": " "},
  {"t": "차지하는", "l": "차지하다"},
  {"t": " ", "l": " "},
  {"t": "비율이", "l": "비율"},
  {"t": " ", "l": " "},
  {"t": "급증하는", "l": "급증하다"},
  {"t": " ", "l": " "},
  {"t": "추세다", "l": "추세"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "이러한", "l": "이러한"},
  {"t": " ", "l": " "},
  {"t": "인구", "l": "인구"},
  {"t": " ", "l": " "},
  {"t": "통계학적", "l": "통계학적"},
  {"t": " ", "l": " "},
  {"t": "변화는", "l": "변화"},
  {"t": " ", "l": " "},
  {"t": "노동력", "l": "노동력"},
  {"t": " ", "l": " "},
  {"t": "부족", "l": "부족"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "잠재성장률", "l": "잠재성장률"},
  {"t": " ", "l": " "},
  {"t": "하락", "l": "하락"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "그리고", "l": "그리고"},
  {"t": " ", "l": " "},
  {"t": "사회보장", "l": "사회보장"},
  {"t": " ", "l": " "},
  {"t": "비용의", "l": "비용"},
  {"t": " ", "l": " "},
  {"t": "폭증이라는", "l": "폭증"},
  {"t": " ", "l": " "},
  {"t": "다각적인", "l": "다각적이다"},
  {"t": " ", "l": " "},
  {"t": "경제적", "l": "경제적"},
  {"t": " ", "l": " "},
  {"t": "문제를", "l": "문제"},
  {"t": " ", "l": " "},
  {"t": "야기하고", "l": "야기하다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "특히", "l": "특히"},
  {"t": " ", "l": " "},
  {"t": "국민연금의", "l": "국민연금"},
  {"t": " ", "l": " "},
  {"t": "재정", "l": "재정"},
  {"t": " ", "l": " "},
  {"t": "고갈", "l": "고갈"},
  {"t": " ", "l": " "},
  {"t": "우려와", "l": "우려"},
  {"t": " ", "l": " "},
  {"t": "건강보험", "l": "건강보험"},
  {"t": " ", "l": " "},
  {"t": "재정", "l": "재정"},
  {"t": " ", "l": " "},
  {"t": "압박은", "l": "압박"},
  {"t": " ", "l": " "},
  {"t": "노후", "l": "노후"},
  {"t": " ", "l": " "},
  {"t": "소득", "l": "소득"},
  {"t": " ", "l": " "},
  {"t": "보장과", "l": "보장"},
  {"t": " ", "l": " "},
  {"t": "의료", "l": "의료"},
  {"t": " ", "l": " "},
  {"t": "복지", "l": "복지"},
  {"t": " ", "l": " "},
  {"t": "제도의", "l": "제도"},
  {"t": " ", "l": " "},
  {"t": "지속", "l": "지속"},
  {"t": " ", "l": " "},
  {"t": "가능성에", "l": "가능성"},
  {"t": " ", "l": " "},
  {"t": "의문을", "l": "의문"},
  {"t": " ", "l": " "},
  {"t": "제기하게", "l": "제기하다"},
  {"t": " ", "l": " "},
  {"t": "만든다", "l": "만들다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "또한", "l": "또한"},
  {"t": " ", "l": " "},
  {"t": "노인", "l": "노인"},
  {"t": " ", "l": " "},
  {"t": "빈곤율과", "l": "빈곤율"},
  {"t": " ", "l": " "},
  {"t": "고독사", "l": "고독사"},
  {"t": " ", "l": " "},
  {"t": "문제가", "l": "문제"},
  {"t": " ", "l": " "},
  {"t": "심각한", "l": "심각하다"},
  {"t": " ", "l": " "},
  {"t": "사회적", "l": "사회적"},
  {"t": " ", "l": " "},
  {"t": "화두로", "l": "화두"},
  {"t": " ", "l": " "},
  {"t": "떠오르고", "l": "떠오르다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "기성세대의", "l": "기성세대"},
  {"t": " ", "l": " "},
  {"t": "은퇴", "l": "은퇴"},
  {"t": " ", "l": " "},
  {"t": "후", "l": "후"},
  {"t": " ", "l": " "},
  {"t": "소득", "l": "소득"},
  {"t": " ", "l": " "},
  {"t": "단절과", "l": "단절"},
  {"t": " ", "l": " "},
  {"t": "핵가족화로", "l": "핵가족화"},
  {"t": " ", "l": " "},
  {"t": "인한", "l": "인하다"},
  {"t": " ", "l": " "},
  {"t": "정서적", "l": "정서적"},
  {"t": " ", "l": " "},
  {"t": "고립은", "l": "고립"},
  {"t": " ", "l": " "},
  {"t": "전통적인", "l": "전통적이다"},
  {"t": " ", "l": " "},
  {"t": "가족", "l": "가족"},
  {"t": " ", "l": " "},
  {"t": "공동체의", "l": "공동체"},
  {"t": " ", "l": " "},
  {"t": "부양", "l": "부양"},
  {"t": " ", "l": " "},
  {"t": "기능을", "l": "기능"},
  {"t": " ", "l": " "},
  {"t": "약화시켰다", "l": "약화시키다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "이를", "l": "이"},
  {"t": " ", "l": " "},
  {"t": "해결하기", "l": "해결하다"},
  {"t": " ", "l": " "},
  {"t": "위해", "l": "위하다"},
  {"t": " ", "l": " "},
  {"t": "정부는", "l": "정부"},
  {"t": " ", "l": " "},
  {"t": "노인", "l": "노인"},
  {"t": " ", "l": " "},
  {"t": "일자리", "l": "일자리"},
  {"t": " ", "l": " "},
  {"t": "창출", "l": "창출"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "지역사회", "l": "지역사회"},
  {"t": " ", "l": " "},
  {"t": "통합", "l": "통합"},
  {"t": " ", "l": " "},
  {"t": "돌봄", "l": "돌봄"},
  {"t": " ", "l": " "},
  {"t": "서비스", "l": "서비스"},
  {"t": " ", "l": " "},
  {"t": "구축", "l": "구축"},
  {"t": " ", "l": " "},
  {"t": "등", "l": "등"},
  {"t": " ", "l": " "},
  {"t": "노인", "l": "노인"},
  {"t": " ", "l": " "},
  {"t": "복지", "l": "복지"},
  {"t": " ", "l": " "},
  {"t": "정책을", "l": "정책"},
  {"t": " ", "l": " "},
  {"t": "다변화하고", "l": "다변화하다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "지속", "l": "지속"},
  {"t": " ", "l": " "},
  {"t": "가능한", "l": "가능하다"},
  {"t": " ", "l": " "},
  {"t": "초고령", "l": "초고령"},
  {"t": " ", "l": " "},
  {"t": "사회를", "l": "사회"},
  {"t": " ", "l": " "},
  {"t": "구축하기", "l": "구축하다"},
  {"t": " ", "l": " "},
  {"t": "위해서는", "l": "위하다"},
  {"t": " ", "l": " "},
  {"t": "단순한", "l": "단순하다"},
  {"t": " ", "l": " "},
  {"t": "복지", "l": "복지"},
  {"t": " ", "l": " "},
  {"t": "수혜", "l": "수혜"},
  {"t": " ", "l": " "},
  {"t": "대상으로서의", "l": "대상"},
  {"t": " ", "l": " "},
  {"t": "노인", "l": "노인"},
  {"t": " ", "l": " "},
  {"t": "지원을", "l": "지원"},
  {"t": " ", "l": " "},
  {"t": "넘어", "l": "넘어"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "고령", "l": "고령"},
  {"t": " ", "l": " "},
  {"t": "인구가", "l": "인구"},
  {"t": " ", "l": " "},
  {"t": "생산적인", "l": "생산적이다"},
  {"t": " ", "l": " "},
  {"t": "사회", "l": "사회"},
  {"t": " ", "l": " "},
  {"t": "활동을", "l": "활동"},
  {"t": " ", "l": " "},
  {"t": "지속할", "l": "지속하다"},
  {"t": " ", "l": " "},
  {"t": "수", "l": "수"},
  {"t": " ", "l": " "},
  {"t": "있는", "l": "있다"},
  {"t": " ", "l": " "},
  {"t": "근로", "l": "근로"},
  {"t": " ", "l": " "},
  {"t": "환경", "l": "환경"},
  {"t": " ", "l": " "},
  {"t": "개선과", "l": "개선"},
  {"t": " ", "l": " "},
  {"t": "사회적", "l": "사회적"},
  {"t": " ", "l": " "},
  {"t": "인식의", "l": "인식"},
  {"t": " ", "l": " "},
  {"t": "대전환이", "l": "대전환"},
  {"t": " ", "l": " "},
  {"t": "병행되어야", "l": "병행하다"},
  {"t": " ", "l": " "},
  {"t": "한다", "l": "하다"},
  {"t": ".", "l": "."}
]'::jsonb
),
(
    '한국의 대학 문화와 취업난',
    'Budaya Universitas dan Kesulitan Mencari Kerja di Korea',
    'University Culture and Job Shortage in Korea',
    '한국에서 대학은 학문 탐구의 장을 넘어 성인으로서 사회에 첫발을 내딛기 전 다양한 자율성을 경험하고 미래를 준비하는 중요한 공간이다. 대학 축제, 동아리 활동, 그리고 학과 간의 유대 관계를 중시하는 엠티(MT) 등은 한국 대학 문화의 활기찬 단면을 보여준다. 그러나 최근 극심한 청년 취업난으로 인해 대학 본연의 문화와 낭만이 위축되고 있다는 지적이 제기되고 있다. 과거의 캠퍼스가 학문적 자유와 사회 변혁에 대한 논의로 가득 찼다면, 오늘날의 캠퍼스는 입학과 동시에 취업을 위한 ''스펙 쌓기'' 경쟁의 장으로 변모했다. 학생들은 높은 학점 관리와 어학 성적 취득, 다양한 자격증 확보, 인턴십 경험 등을 쌓기 위해 방학조차 반납한 채 분투하고 있다. 이로 인해 학생들 간의 유대감이 약화되고 개인주의가 심화되는 부작용도 나타나고 있다. 이러한 문제를 해결하기 위해서는 기업의 채용 방식 다변화와 학위 중심의 평가에서 탈피한 직무 능력 중심 평가의 정착이 필요하며, 정부 차원에서도 대학 교육이 시장의 인력 수요와 어긋나지 않도록 학과 구조 개편과 실무 중심 교육 프로그램을 지속적으로 지원해야 한다.',
    'Di Korea, universitas melampaui sekadar tempat penyelidikan akademis, menjadi ruang penting untuk mengalami berbagai otonomi dan mempersiapkan masa depan sebelum melangkah ke masyarakat sebagai orang dewasa. Festival universitas, kegiatan klub, dan MT (Membership Training) yang mementingkan ikatan antar departemen menampilkan aspek dinamis dari budaya universitas Korea. Namun, baru-baru ini ada kritik bahwa budaya asli dan romansa universitas sedang menyusut karena parahnya kesulitan mencari pekerjaan bagi kaum muda. Jika kampus di masa lalu dipenuhi diskusi tentang kebebasan akademis dan transformasi sosial, kampus saat ini telah berubah menjadi medan kompetisi untuk ''membangun spesifikasi (spec)'' demi pekerjaan segera setelah masuk. Mahasiswa berjuang bahkan mengorbankan liburan mereka demi mempertahankan IPK tinggi, memperoleh nilai bahasa asing, mendapatkan sertifikat keahlian, dan mengumpulkan pengalaman magang. Akibatnya, efek samping seperti melemahnya rasa ikatan di antara mahasiswa dan meningkatnya individualisme juga muncul. Untuk menyelesaikan masalah ini, diperlukan diversifikasi metode perekrutan perusahaan dan pemantapan evaluasi berbasis kemampuan kerja yang melepaskan diri dari penilaian berbasis gelar. Dari sisi pemerintah, dukungan berkelanjutan harus diberikan untuk reorganisasi struktur departemen and program pendidikan praktis agar pendidikan universitas tidak meleset dari permintaan tenaga kerja pasar.',
    'In Korea, a university goes beyond a place of academic pursuit to become an important space for experiencing autonomy and preparing for the future before stepping into society as an adult. University festivals, club activities, and MTs (Membership Training) that emphasize bonding between departments show the vibrant side of Korean university culture. However, recently, critics point out that the inherent culture and romance of universities are shrinking due to severe youth unemployment. If the campuses of the past were filled with discussions on academic freedom and social change, today''s campuses have transformed into arenas of competition to ''build specs'' for employment upon admission. Students struggle, even giving up their vacations, to maintain high GPAs, acquire language test scores, secure various certifications, and stack internship experiences. Consequently, side effects such as weakened bonding among students and intensified individualism are also appearing. To resolve these issues, diversifying corporate recruitment methods and establishing job-competency-based evaluation away from degree-oriented evaluation are required. On the government side, continuous support should be provided for departmental restructuring and practical educational programs so that university education does not misalign with market labor demands.',
    'advanced',
    'education',
    'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "한국", "l": "한국"},
  {"t": "에서", "l": "에서"},
  {"t": " ", "t": " "},
  {"t": "대학", "l": "대학"},
  {"t": "은", "l": "은"},
  {"t": " ", "t": " "},
  {"t": "학문", "l": "학문"},
  {"t": " ", "t": " "},
  {"t": "탐구", "l": "탐구"},
  {"t": "의", "l": "의"},
  {"t": " ", "t": " "},
  {"t": "장", "l": "장"},
  {"t": "을", "l": "을"},
  {"t": " ", "t": " "},
  {"t": "넘어", "l": "넘다"},
  {"t": " ", "t": " "},
  {"t": "성인", "l": "성인"},
  {"t": "으로서", "l": "으로서"},
  {"t": " ", "t": " "},
  {"t": "사회", "l": "사회"},
  {"t": "에", "l": "에"},
  {"t": " ", "t": " "},
  {"t": "첫발", "l": "첫발"},
  {"t": "을", "l": "을"},
  {"t": " ", "t": " "},
  {"t": "내딛기", "l": "내딛다"},
  {"t": " ", "t": " "},
  {"t": "전", "l": "전"},
  {"t": " ", "t": " "},
  {"t": "다양한", "l": "다양하다"},
  {"t": " ", "t": " "},
  {"t": "자율성", "l": "자율성"},
  {"t": "을", "l": "을"},
  {"t": " ", "t": " "},
  {"t": "경험", "l": "경험"},
  {"t": "하고", "l": "하다"},
  {"t": " ", "t": " "},
  {"t": "미래", "l": "미래"},
  {"t": "를", "l": "를"},
  {"t": " ", "t": " "},
  {"t": "준비", "l": "준비"},
  {"t": "하는", "l": "하다"},
  {"t": " ", "t": " "},
  {"t": "중요한", "l": "중요하다"},
  {"t": " ", "t": " "},
  {"t": "공간", "l": "공간"},
  {"t": "이다", "l": "이다"},
  {"t": ".", "t": "."},
  {"t": " ", "t": " "},
  {"t": "대학", "l": "대학"},
  {"t": " ", "t": " "},
  {"t": "축제", "l": "축제"},
  {"t": ",", "t": ","},
  {"t": " ", "t": " "},
  {"t": "동아리", "l": "동아리"},
  {"t": " ", "t": " "},
  {"t": "활동", "l": "활동"},
  {"t": ",", "t": ","},
  {"t": " ", "t": " "},
  {"t": "그리고", "l": "그리고"},
  {"t": " ", "t": " "},
  {"t": "학과", "l": "학과"},
  {"t": " ", "t": " "},
  {"t": "간", "l": "간"},
  {"t": "의", "l": "의"},
  {"t": " ", "t": " "},
  {"t": "유대", "l": "유대"},
  {"t": " ", "t": " "},
  {"t": "관계", "l": "관계"},
  {"t": "를", "l": "를"},
  {"t": " ", "t": " "},
  {"t": "중시", "l": "중시"},
  {"t": "하는", "l": "하다"},
  {"t": " ", "t": " "},
  {"t": "엠티", "l": "엠티"},
  {"t": "(", "t": "("},
  {"t": "MT", "t": "MT"},
  {"t": ")", "t": ")"},
  {"t": " ", "t": " "},
  {"t": "등", "l": "등"},
  {"t": "은", "l": "은"},
  {"t": " ", "t": " "},
  {"t": "한국", "l": "한국"},
  {"t": " ", "t": " "},
  {"t": "대학", "l": "대학"},
  {"t": " ", "t": " "},
  {"t": "문화", "l": "문화"},
  {"t": "의", "l": "의"},
  {"t": " ", "t": " "},
  {"t": "활기찬", "l": "활기차다"},
  {"t": " ", "t": " "},
  {"t": "단면", "l": "단면"},
  {"t": "을", "l": "을"},
  {"t": " ", "t": " "},
  {"t": "보여준다", "l": "보여주다"},
  {"t": ".", "t": "."},
  {"t": " ", "t": " "},
  {"t": "그러나", "l": "그러나"},
  {"t": " ", "t": " "},
  {"t": "최근", "l": "최근"},
  {"t": " ", "t": " "},
  {"t": "극심한", "l": "극심하다"},
  {"t": " ", "t": " "},
  {"t": "청년", "l": "청년"},
  {"t": " ", "t": " "},
  {"t": "취업난", "l": "취업난"},
  {"t": "으로", "l": "으로"},
  {"t": " ", "t": " "},
  {"t": "인해", "l": "인하다"},
  {"t": " ", "t": " "},
  {"t": "대학", "l": "대학"},
  {"t": " ", "t": " "},
  {"t": "본연", "l": "본연"},
  {"t": "의", "l": "의"},
  {"t": " ", "t": " "},
  {"t": "문화", "l": "문화"},
  {"t": "와", "l": "와"},
  {"t": " ", "t": " "},
  {"t": "낭만", "l": "낭만"},
  {"t": "이", "l": "이"},
  {"t": " ", "t": " "},
  {"t": "위축", "l": "위축"},
  {"t": "되고", "l": "되다"},
  {"t": " ", "t": " "},
  {"t": "있다", "l": "있다"},
  {"t": "는", "l": "다"},
  {"t": " ", "t": " "},
  {"t": "지적", "l": "지적"},
  {"t": "이", "l": "이"},
  {"t": " ", "t": " "},
  {"t": "제기", "l": "제기"},
  {"t": "되고", "l": "되다"},
  {"t": " ", "t": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "t": "."},
  {"t": " ", "t": " "},
  {"t": "과거", "l": "과거"},
  {"t": "의", "l": "의"},
  {"t": " ", "t": " "},
  {"t": "캠퍼스", "l": "캠퍼스"},
  {"t": "가", "l": "가"},
  {"t": " ", "t": " "},
  {"t": "학문적", "l": "학문적"},
  {"t": " ", "t": " "},
  {"t": "자유", "l": "자유"},
  {"t": "와", "l": "와"},
  {"t": " ", "t": " "},
  {"t": "사회", "l": "사회"},
  {"t": " ", "t": " "},
  {"t": "변혁", "l": "변혁"},
  {"t": "에", "l": "에"},
  {"t": " ", "t": " "},
  {"t": "대한", "l": "대하다"},
  {"t": " ", "t": " "},
  {"t": "논의", "l": "논의"},
  {"t": "로", "l": "로"},
  {"t": " ", "t": " "},
  {"t": "가득", "l": "가득"},
  {"t": " ", "t": " "},
  {"t": "찼", "l": "차다"},
  {"t": "다면", "l": "다면"},
  {"t": ",", "t": ","},
  {"t": " ", "t": " "},
  {"t": "오늘날", "l": "오늘날"},
  {"t": "의", "l": "의"},
  {"t": " ", "t": " "},
  {"t": "캠퍼스", "l": "캠퍼스"},
  {"t": "는", "l": "다"},
  {"t": " ", "t": " "},
  {"t": "입학", "l": "입학"},
  {"t": "과", "l": "과"},
  {"t": " ", "t": " "},
  {"t": "동시", "l": "동시"},
  {"t": "에", "l": "에"},
  {"t": " ", "t": " "},
  {"t": "취업", "l": "취업"},
  {"t": "을", "l": "을"},
  {"t": " ", "t": " "},
  {"t": "위한", "l": "위하다"},
  {"t": " ", "t": " "},
  {"t": "''", "t": "''"},
  {"t": "스펙", "l": "스펙"},
  {"t": " ", "t": " "},
  {"t": "쌓기", "l": "쌓다"},
  {"t": "''", "t": "''"},
  {"t": " ", "t": " "},
  {"t": "경쟁", "l": "경쟁"},
  {"t": "의", "l": "의"},
  {"t": " ", "t": " "},
  {"t": "장", "l": "장"},
  {"t": "으로", "l": "으로"},
  {"t": " ", "t": " "},
  {"t": "변모", "l": "변모"},
  {"t": "했다", "l": "변모하다"},
  {"t": ".", "t": "."},
  {"t": " ", "t": " "},
  {"t": "학생", "l": "학생"},
  {"t": "들", "l": "들"},
  {"t": "은", "l": "은"},
  {"t": " ", "t": " "},
  {"t": "높은", "l": "높다"},
  {"t": " ", "t": " "},
  {"t": "학점", "l": "학점"},
  {"t": " ", "t": " "},
  {"t": "관리", "l": "관리"},
  {"t": "와", "l": "와"},
  {"t": " ", "t": " "},
  {"t": "어학", "l": "어학"},
  {"t": " ", "t": " "},
  {"t": "성적", "l": "성적"},
  {"t": " ", "t": " "},
  {"t": "취득", "l": "취득"},
  {"t": ",", "t": ","},
  {"t": " ", "t": " "},
  {"t": "다양한", "l": "다양하다"},
  {"t": " ", "t": " "},
  {"t": "자격증", "l": "자격증"},
  {"t": " ", "t": " "},
  {"t": "확보", "l": "확보"},
  {"t": ",", "t": ","},
  {"t": " ", "t": " "},
  {"t": "인턴십", "l": "인턴십"},
  {"t": " ", "t": " "},
  {"t": "경험", "l": "경험"},
  {"t": " ", "t": " "},
  {"t": "등", "l": "등"},
  {"t": "을", "l": "을"},
  {"t": " ", "t": " "},
  {"t": "쌓기", "l": "쌓다"},
  {"t": " ", "t": " "},
  {"t": "위해", "l": "위하다"},
  {"t": " ", "t": " "},
  {"t": "방학", "l": "방학"},
  {"t": "조차", "l": "조차"},
  {"t": " ", "t": " "},
  {"t": "반납", "l": "반납"},
  {"t": "한", "l": "하다"},
  {"t": " ", "t": " "},
  {"t": "채", "l": "채"},
  {"t": " ", "t": " "},
  {"t": "분투", "l": "분투"},
  {"t": "하고", "l": "하다"},
  {"t": " ", "t": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "t": "."},
  {"t": " ", "t": " "},
  {"t": "이로", "l": "이렇다"},
  {"t": " ", "t": " "},
  {"t": "인해", "l": "인하다"},
  {"t": " ", "t": " "},
  {"t": "학생", "l": "학생"},
  {"t": "들", "l": "들"},
  {"t": " ", "t": " "},
  {"t": "간", "l": "간"},
  {"t": "의", "l": "의"},
  {"t": " ", "t": " "},
  {"t": "유대감", "l": "유대감"},
  {"t": "이", "l": "이"},
  {"t": " ", "t": " "},
  {"t": "약화", "l": "약화"},
  {"t": "되고", "l": "되다"},
  {"t": " ", "t": " "},
  {"t": "있으며", "l": "있다"},
  {"t": " ", "t": " "},
  {"t": "개인주의", "l": "개인주의"},
  {"t": "가", "l": "가"},
  {"t": " ", "t": " "},
  {"t": "심화", "l": "심화"},
  {"t": "되는", "l": "되다"},
  {"t": " ", "t": " "},
  {"t": "부작용", "l": "부작용"},
  {"t": "도", "l": "도"},
  {"t": " ", "t": " "},
  {"t": "나타나", "l": "나타나다"},
  {"t": "고", "l": "고"},
  {"t": " ", "t": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "t": "."},
  {"t": " ", "t": " "},
  {"t": "이러한", "l": "이러한"},
  {"t": " ", "t": " "},
  {"t": "문제", "l": "문제"},
  {"t": "를", "l": "를"},
  {"t": " ", "t": " "},
  {"t": "해결", "l": "해결"},
  {"t": "하기", "l": "하다"},
  {"t": " ", "t": " "},
  {"t": "위해서", "l": "위하다"},
  {"t": "는", "l": "다"},
  {"t": " ", "t": " "},
  {"t": "기업", "l": "기업"},
  {"t": "의", "l": "의"},
  {"t": " ", "t": " "},
  {"t": "채용", "l": "채용"},
  {"t": " ", "t": " "},
  {"t": "방식", "l": "방식"},
  {"t": " ", "t": " "},
  {"t": "다변화", "l": "다변화"},
  {"t": "와", "l": "와"},
  {"t": " ", "t": " "},
  {"t": "학위", "l": "학위"},
  {"t": " ", "t": " "},
  {"t": "중심", "l": "중심"},
  {"t": "의", "l": "의"},
  {"t": " ", "t": " "},
  {"t": "평가", "l": "평가"},
  {"t": "에서", "l": "에서"},
  {"t": " ", "t": " "},
  {"t": "탈피", "l": "탈피"},
  {"t": "한", "l": "하다"},
  {"t": " ", "t": " "},
  {"t": "직무", "l": "직무"},
  {"t": " ", "t": " "},
  {"t": "능력", "l": "능력"},
  {"t": " ", "t": " "},
  {"t": "중심", "l": "중심"},
  {"t": " ", "t": " "},
  {"t": "평가", "l": "평가"},
  {"t": "의", "l": "의"},
  {"t": " ", "t": " "},
  {"t": "정착", "l": "정착"},
  {"t": "이", "l": "이"},
  {"t": " ", "t": " "},
  {"t": "필요", "l": "필요"},
  {"t": "하며", "l": "하다"},
  {"t": ",", "t": ","},
  {"t": " ", "t": " "},
  {"t": "정부", "l": "정부"},
  {"t": " ", "t": " "},
  {"t": "차원", "l": "차원"},
  {"t": "에서도", "l": "에서도"},
  {"t": " ", "t": " "},
  {"t": "대학", "l": "대학"},
  {"t": " ", "t": " "},
  {"t": "교육", "l": "교육"},
  {"t": "이", "l": "이"},
  {"t": " ", "t": " "},
  {"t": "시장", "l": "시장"},
  {"t": "의", "l": "의"},
  {"t": " ", "t": " "},
  {"t": "인력", "l": "인력"},
  {"t": " ", "t": " "},
  {"t": "수요", "l": "수요"},
  {"t": "와", "l": "와"},
  {"t": " ", "t": " "},
  {"t": "어긋나", "l": "어긋나다"},
  {"t": "지", "l": "지"},
  {"t": " ", "t": " "},
  {"t": "않도록", "l": "않다"},
  {"t": " ", "t": " "},
  {"t": "학과", "l": "학과"},
  {"t": " ", "t": " "},
  {"t": "구조", "l": "구조"},
  {"t": " ", "t": " "},
  {"t": "개편", "l": "개편"},
  {"t": "과", "l": "과"},
  {"t": " ", "t": " "},
  {"t": "실무", "l": "실무"},
  {"t": " ", "t": " "},
  {"t": "중심", "l": "중심"},
  {"t": " ", "t": " "},
  {"t": "교육", "l": "교육"},
  {"t": " ", "t": " "},
  {"t": "프로그램", "l": "프로그램"},
  {"t": "을", "l": "을"},
  {"t": " ", "t": " "},
  {"t": "지속적으로", "l": "지속적으로"},
  {"t": " ", "t": " "},
  {"t": "지원", "l": "지원"},
  {"t": "해야", "l": "해야"},
  {"t": " ", "t": " "},
  {"t": "한다", "l": "하다"},
  {"t": ".", "t": "."}
]'::jsonb
),
(
    '한국의 인공지능 산업의 미래',
    'Masa Depan Industri AI di Korea',
    'The Future of Korea''s AI Industry',
    '인공지능 기술이 글로벌 산업의 새로운 게임 체인저로 부상함에 따라 한국 역시 국가적 역량을 집중하여 AI 산업 육성에 박차를 가하고 있다. 한국은 세계적인 반도체 제조 기술과 초고속 통신망을 보유하고 있어, 하드웨어와 인프라 측면에서 강력한 경쟁력을 지닌다. 특히 차세대 AI 반도체인 HBM과 NPU의 개발은 고성능 인공지능 연산 처리를 위한 필수 기술로서 글로벌 시장에서 주목을 받고 있다. 그러나 소프트웨어와 알고리즘 부문에서는 빅테크 기업들이 주도하는 글로벌 표준과의 격차를 좁혀야 하는 과제가 있다. 한국 기업들은 독자적인 초거대 AI 언어 모델을 개발하고, 한국어와 아시아 문화권의 맥락에 최적화된 특화 서비스를 선보이며 틈새시장을 공략하고 있다. 의료, 금융, 제조 등 이종 산업과의 융합을 통한 AI 실증 사업 역시 활발하게 진행되고 있다. 향후 AI 산업의 지속적인 번영을 위해서는 우수한 연구 개발 인력 양성, 고성능 컴퓨팅 인프라 지원 확대, 그리고 AI 윤리 가이드라인 수립을 통한 안전한 활용 기준 마련이 입체적으로 추진되어야 할 것이다.',
    'Seiring teknologi kecerdasan buatan (AI) muncul sebagai pengubah permainan (game changer) baru dalam industri global, Korea juga mempercepat pembinaan industri AI dengan memusatkan kapabilitas nasionalnya. Korea memiliki teknologi semikonduktor kelas dunia dan jaringan komunikasi super cepat, sehingga memiliki daya saing yang kuat dalam hal perangkat keras dan infrastruktur. Secara khusus, pengembangan semikonduktor AI generasi berikutnya seperti HBM dan NPU mendapat perhatian di pasar global sebagai teknologi esensial untuk pemrosesan AI kinerja tinggi. Namun, di sektor perangkat lunak dan algoritma, ada tantangan untuk memperkecil kesenjangan dengan standar global yang dipimpin oleh big tech. Perusahaan Korea menargetkan pasar khusus dengan mengembangkan model bahasa AI super besar mereka sendiri dan menghadirkan layanan khusus yang dioptimalkan untuk konteks bahasa Korea dan wilayah budaya Asia. Bisnis demonstrasi AI melalui konvergensi dengan industri lain seperti medis, keuangan, dan manufaktur juga berjalan aktif. Demi kemakmuran berkelanjutan industri AI di masa depan, pembinaan talenta R&D yang unggul, perluasan dukungan infrastruktur komputasi kinerja tinggi, dan penyusunan standar penggunaan yang aman melalui penetapan pedoman etika AI harus didorong secara tiga dimensi.',
    'As artificial intelligence technology emerges as a new game changer in the global industry, Korea is also accelerating the cultivation of the AI industry by concentrating its national capabilities. Korea possesses world-class semiconductor manufacturing technology and super-high-speed communication networks, giving it strong competitiveness in hardware and infrastructure. In particular, the development of next-generation AI semiconductors such as HBM and NPU is drawing attention in the global market as an essential technology for high-performance AI computing. However, in the software and algorithm sectors, there is a challenge to narrow the gap with global standards led by big tech companies. Korean companies are targeting niche markets by developing their own hyper-scale AI language models and introducing specialized services optimized for the context of Korean and Asian cultures. AI demonstration projects through convergence with other industries such as healthcare, finance, and manufacturing are also actively underway. For the continuous prosperity of the AI industry in the future, nurturing excellent R&D talent, expanding support for high-performance computing infrastructure, and establishing safety standards through the formation of AI ethics guidelines must be pushed forward in a multi-dimensional way.',
    'advanced',
    'technology',
    'https://images.unsplash.com/photo-1677442136019-21780efad99a?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "인공지능", "l": "인공지능"},
  {"t": " ", "l": " "},
  {"t": "기술이", "l": "기술"},
  {"t": " ", "l": " "},
  {"t": "글로벌", "l": "글로벌"},
  {"t": " ", "l": " "},
  {"t": "산업의", "l": "산업"},
  {"t": " ", "l": " "},
  {"t": "새로운", "l": "새로운"},
  {"t": " ", "l": " "},
  {"t": "게임", "l": "게임"},
  {"t": " ", "l": " "},
  {"t": "체인저로", "l": "체인저"},
  {"t": " ", "l": " "},
  {"t": "부상함에", "l": "부상하다"},
  {"t": " ", "l": " "},
  {"t": "따라", "l": "따르다"},
  {"t": " ", "l": " "},
  {"t": "한국", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "역시", "l": "역시"},
  {"t": " ", "l": " "},
  {"t": "국가적", "l": "국가적"},
  {"t": " ", "l": " "},
  {"t": "역량을", "l": "역량"},
  {"t": " ", "l": " "},
  {"t": "집중하여", "l": "집중하다"},
  {"t": " ", "l": " "},
  {"t": "AI", "l": "AI"},
  {"t": " ", "l": " "},
  {"t": "산업", "l": "산업"},
  {"t": " ", "l": " "},
  {"t": "육성에", "l": "육성"},
  {"t": " ", "l": " "},
  {"t": "박차를", "l": "박차"},
  {"t": " ", "l": " "},
  {"t": "가하고", "l": "가하다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "한국은", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "세계적인", "l": "세계적"},
  {"t": " ", "l": " "},
  {"t": "반도체", "l": "반도체"},
  {"t": " ", "l": " "},
  {"t": "제조", "l": "제조"},
  {"t": " ", "l": " "},
  {"t": "기술과", "l": "기술"},
  {"t": " ", "l": " "},
  {"t": "초고속", "l": "초고속"},
  {"t": " ", "l": " "},
  {"t": "통신망을", "l": "통신망"},
  {"t": " ", "l": " "},
  {"t": "보유하고", "l": "보유하다"},
  {"t": " ", "l": " "},
  {"t": "있어", "l": "있다"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "하드웨어와", "l": "하드웨어"},
  {"t": " ", "l": " "},
  {"t": "인프라", "l": "인프라"},
  {"t": " ", "l": " "},
  {"t": "측면에서", "l": "측면"},
  {"t": " ", "l": " "},
  {"t": "강력한", "l": "강력하다"},
  {"t": " ", "l": " "},
  {"t": "경쟁력을", "l": "경쟁력"},
  {"t": " ", "l": " "},
  {"t": "지닌다", "l": "지니다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "특히", "l": "특히"},
  {"t": " ", "l": " "},
  {"t": "차세대", "l": "차세대"},
  {"t": " ", "l": " "},
  {"t": "AI", "l": "AI"},
  {"t": " ", "l": " "},
  {"t": "반도체인", "l": "반도체"},
  {"t": " ", "l": " "},
  {"t": "HBM과", "l": "HBM"},
  {"t": " ", "l": " "},
  {"t": "NPU의", "l": "NPU"},
  {"t": " ", "l": " "},
  {"t": "개발은", "l": "개발"},
  {"t": " ", "l": " "},
  {"t": "고성능", "l": "고성능"},
  {"t": " ", "l": " "},
  {"t": "인공지능", "l": "인공지능"},
  {"t": " ", "l": " "},
  {"t": "연산", "l": "연산"},
  {"t": " ", "l": " "},
  {"t": "처리를", "l": "처리"},
  {"t": " ", "l": " "},
  {"t": "위한", "l": "위하다"},
  {"t": " ", "l": " "},
  {"t": "필수", "l": "필수"},
  {"t": " ", "l": " "},
  {"t": "기술로서", "l": "기술"},
  {"t": " ", "l": " "},
  {"t": "글로벌", "l": "글로벌"},
  {"t": " ", "l": " "},
  {"t": "시장에서", "l": "시장"},
  {"t": " ", "l": " "},
  {"t": "주목을", "l": "주목"},
  {"t": " ", "l": " "},
  {"t": "받고", "l": "받다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "그러나", "l": "그러나"},
  {"t": " ", "l": " "},
  {"t": "소프트웨어와", "l": "소프트웨어"},
  {"t": " ", "l": " "},
  {"t": "알고리즘", "l": "알고리즘"},
  {"t": " ", "l": " "},
  {"t": "부문에서는", "l": "부문"},
  {"t": " ", "l": " "},
  {"t": "빅테크", "l": "빅테크"},
  {"t": " ", "l": " "},
  {"t": "기업들이", "l": "기업"},
  {"t": " ", "l": " "},
  {"t": "주도하는", "l": "주도하다"},
  {"t": " ", "l": " "},
  {"t": "글로벌", "l": "글로벌"},
  {"t": " ", "l": " "},
  {"t": "표준과의", "l": "표준"},
  {"t": " ", "l": " "},
  {"t": "격차를", "l": "격차"},
  {"t": " ", "l": " "},
  {"t": "좁혀야", "l": "좁히다"},
  {"t": " ", "l": " "},
  {"t": "하는", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "과제가", "l": "과제"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "한국", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "기업들은", "l": "기업"},
  {"t": " ", "l": " "},
  {"t": "독자적인", "l": "독자적"},
  {"t": " ", "l": " "},
  {"t": "초거대", "l": "초거대"},
  {"t": " ", "l": " "},
  {"t": "AI", "l": "AI"},
  {"t": " ", "l": " "},
  {"t": "언어", "l": "언어"},
  {"t": " ", "l": " "},
  {"t": "모델을", "l": "모델"},
  {"t": " ", "l": " "},
  {"t": "개발하고", "l": "개발하다"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "한국어와", "l": "한국어"},
  {"t": " ", "l": " "},
  {"t": "아시아", "l": "아시아"},
  {"t": " ", "l": " "},
  {"t": "문화권의", "l": "문화권"},
  {"t": " ", "l": " "},
  {"t": "맥락에", "l": "맥락"},
  {"t": " ", "l": " "},
  {"t": "최적화된", "l": "최적화하다"},
  {"t": " ", "l": " "},
  {"t": "특화", "l": "특화"},
  {"t": " ", "l": " "},
  {"t": "서비스를", "l": "서비스"},
  {"t": " ", "l": " "},
  {"t": "선보이며", "l": "선보이다"},
  {"t": " ", "l": " "},
  {"t": "틈새시장을", "l": "틈새시장"},
  {"t": " ", "l": " "},
  {"t": "공략하고", "l": "공략하다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "의료", "l": "의료"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "금융", "l": "금융"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "제조", "l": "제조"},
  {"t": " ", "l": " "},
  {"t": "등", "l": "등"},
  {"t": " ", "l": " "},
  {"t": "이종", "l": "이종"},
  {"t": " ", "l": " "},
  {"t": "산업과의", "l": "산업"},
  {"t": " ", "l": " "},
  {"t": "융합을", "l": "융합"},
  {"t": " ", "l": " "},
  {"t": "통한", "l": "통하다"},
  {"t": " ", "l": " "},
  {"t": "AI", "l": "AI"},
  {"t": " ", "l": " "},
  {"t": "실증", "l": "실증"},
  {"t": " ", "l": " "},
  {"t": "사업", "l": "사업"},
  {"t": " ", "l": " "},
  {"t": "역시", "l": "역시"},
  {"t": " ", "l": " "},
  {"t": "활발하게", "l": "활발하다"},
  {"t": " ", "l": " "},
  {"t": "진행되고", "l": "진행되다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "향후", "l": "향후"},
  {"t": " ", "l": " "},
  {"t": "AI", "l": "AI"},
  {"t": " ", "l": " "},
  {"t": "산업의", "l": "산업"},
  {"t": " ", "l": " "},
  {"t": "지속적인", "l": "지속적"},
  {"t": " ", "l": " "},
  {"t": "번영을", "l": "번영"},
  {"t": " ", "l": " "},
  {"t": "위해서는", "l": "위하다"},
  {"t": " ", "l": " "},
  {"t": "우수한", "l": "우수하다"},
  {"t": " ", "l": " "},
  {"t": "연구", "l": "연구"},
  {"t": " ", "l": " "},
  {"t": "개발", "l": "개발"},
  {"t": " ", "l": " "},
  {"t": "인력", "l": "인력"},
  {"t": " ", "l": " "},
  {"t": "양성", "l": "양성"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "고성능", "l": "고성능"},
  {"t": " ", "l": " "},
  {"t": "컴퓨팅", "l": "컴퓨팅"},
  {"t": " ", "l": " "},
  {"t": "인프라", "l": "인프라"},
  {"t": " ", "l": " "},
  {"t": "지원", "l": "지원"},
  {"t": " ", "l": " "},
  {"t": "확대", "l": "확대"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "그리고", "l": "그리고"},
  {"t": " ", "l": " "},
  {"t": "AI", "l": "AI"},
  {"t": " ", "l": " "},
  {"t": "윤리", "l": "윤리"},
  {"t": " ", "l": " "},
  {"t": "가이드라인", "l": "가이드라인"},
  {"t": " ", "l": " "},
  {"t": "수립을", "l": "수립"},
  {"t": " ", "l": " "},
  {"t": "통한", "l": "통하다"},
  {"t": " ", "l": " "},
  {"t": "안전한", "l": "안전하다"},
  {"t": " ", "l": " "},
  {"t": "활용", "l": "활용"},
  {"t": " ", "l": " "},
  {"t": "기준", "l": "기준"},
  {"t": " ", "l": " "},
  {"t": "마련이", "l": "마련"},
  {"t": " ", "l": " "},
  {"t": "입체적으로", "l": "입체적"},
  {"t": " ", "l": " "},
  {"t": "추진되어야", "l": "추진되다"},
  {"t": " ", "l": " "},
  {"t": "할", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "것이다", "l": "것이다"}
]'::jsonb
);