-- Migration: 014_add_more_stories_part3.sql
-- Description: Add another 3 intermediate and 3 advanced stories with interactive word tokens

INSERT INTO public.stories (
    title_ko,
    title_id,
    title_en,
    content_ko,
    content_id,
    content_en,
    level,
    category,
    cover_image_url,
    is_published,
    content_tokens
) VALUES
(
    '한국의 설날',
    'Hari Raya Seollal di Korea',
    'Seollal - Korean Lunar New Year',
    '설날은 한국의 가장 큰 명절 중 하나로, 음력 1월 1일이에요. 설날 아침에는 온 가족이 모여서 조상님께 차례를 지내고 떡국을 먹어요. 떡국을 먹으면 나이를 한 살 더 먹는다고 해요. 그리고 부모님과 어른들께 세배를 드리며 건강과 복을 빌어요. 세배를 하면 어른들께서 세뱃돈을 주시며 덕담을 해 주세요. 설날에는 가족들과 함께 윷놀이나 제기차기 같은 전통 놀이를 하면서 즐거운 시간을 보내요.',
    'Seollal adalah salah satu hari raya terbesar di Korea, jatuh pada tanggal 1 Januari penanggalan lunar (imlek). Pada pagi hari Seollal, seluruh keluarga berkumpul untuk melakukan upacara penghormatan leluhur (Charye) dan menyantap Tteokguk (sup kue beras). Konon, memakan Tteokguk menandakan bertambahnya usia satu tahun. Kemudian, mereka melakukan sungkem (Sebae) kepada orang tua dan sesepuh untuk mendoakan kesehatan dan keberuntungan. Sebagai gantinya, sesepuh memberikan uang tahun baru (Sebaetdon) beserta petuah bijak. Pada hari Seollal, mereka menghabiskan waktu menyenangkan bersama keluarga dengan bermain permainan tradisional seperti Yutnori atau Jegichagi.',
    'Seollal is one of the biggest holidays in Korea, celebrated on January 1st of the lunar calendar. On the morning of Seollal, the whole family gathers to perform ancestral rites (Charye) and eat Tteokguk (rice cake soup). Eating Tteokguk is said to mean growing one year older. Then, they bow (Sebae) to parents and elders to wish them health and good fortune. When they bow, the elders give them new year''s money (Sebaetdon) and words of wisdom. On Seollal, family members spend pleasant time together playing traditional games like Yutnori or Jegichagi.',
    'intermediate',
    'k_culture',
    'https://images.unsplash.com/photo-1618220179428-22790b461013?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "설날은", "l": "설날"},
  {"t": " ", "l": " "},
  {"t": "한국의", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "가장", "l": "가장"},
  {"t": " ", "l": " "},
  {"t": "큰", "l": "크다"},
  {"t": " ", "l": " "},
  {"t": "명절", "l": "명절"},
  {"t": " ", "l": " "},
  {"t": "중", "l": "중"},
  {"t": " ", "l": " "},
  {"t": "하나로", "l": "하나"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "음력", "l": "음력"},
  {"t": " ", "l": " "},
  {"t": "1월", "l": "1월"},
  {"t": " ", "l": " "},
  {"t": "1일이에요", "l": "이다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "설날", "l": "설날"},
  {"t": " ", "l": " "},
  {"t": "아침에는", "l": "아침"},
  {"t": " ", "l": " "},
  {"t": "온", "l": "온"},
  {"t": " ", "l": " "},
  {"t": "가족이", "l": "가족"},
  {"t": " ", "l": " "},
  {"t": "모여서", "l": "모이다"},
  {"t": " ", "l": " "},
  {"t": "조상님께", "l": "조상님"},
  {"t": " ", "l": " "},
  {"t": "차례를", "l": "차례"},
  {"t": " ", "l": " "},
  {"t": "지내고", "l": "지내다"},
  {"t": " ", "l": " "},
  {"t": "떡국을", "l": "떡국"},
  {"t": " ", "l": " "},
  {"t": "먹어요", "l": "먹다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "떡국을", "l": "떡국"},
  {"t": " ", "l": " "},
  {"t": "먹으면", "l": "먹다"},
  {"t": " ", "l": " "},
  {"t": "나이를", "l": "나이"},
  {"t": " ", "l": " "},
  {"t": "한", "l": "한"},
  {"t": " ", "l": " "},
  {"t": "살", "l": "살"},
  {"t": " ", "l": " "},
  {"t": "더", "l": "더"},
  {"t": " ", "l": " "},
  {"t": "먹는다고", "l": "먹다"},
  {"t": " ", "l": " "},
  {"t": "해요", "l": "하다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "그리고", "l": "그리고"},
  {"t": " ", "l": " "},
  {"t": "부모님과", "l": "부모님"},
  {"t": " ", "l": " "},
  {"t": "어른들께", "l": "어른"},
  {"t": " ", "l": " "},
  {"t": "세배를", "l": "세배"},
  {"t": " ", "l": " "},
  {"t": "드리며", "l": "드리다"},
  {"t": " ", "l": " "},
  {"t": "건강과", "l": "건강"},
  {"t": " ", "l": " "},
  {"t": "복을", "l": "복"},
  {"t": " ", "l": " "},
  {"t": "빌어요", "l": "빌다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "세배를", "l": "세배"},
  {"t": " ", "l": " "},
  {"t": "하면", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "어른들께서", "l": "어른"},
  {"t": " ", "l": " "},
  {"t": "세뱃돈을", "l": "세뱃돈"},
  {"t": " ", "l": " "},
  {"t": "주시며", "l": "주시다"},
  {"t": " ", "l": " "},
  {"t": "덕담을", "l": "덕담"},
  {"t": " ", "l": " "},
  {"t": "해", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "주세요", "l": "하다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "설날에는", "l": "설날"},
  {"t": " ", "l": " "},
  {"t": "가족들과", "l": "가족"},
  {"t": " ", "l": " "},
  {"t": "함께", "l": "함께"},
  {"t": " ", "l": " "},
  {"t": "윷놀이나", "l": "윷놀이"},
  {"t": " ", "l": " "},
  {"t": "제기차기", "l": "제기차기"},
  {"t": " ", "l": " "},
  {"t": "같은", "l": "같다"},
  {"t": " ", "l": " "},
  {"t": "전통", "l": "전통"},
  {"t": " ", "l": " "},
  {"t": "놀이를", "l": "놀이"},
  {"t": " ", "l": " "},
  {"t": "하면서", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "즐거운", "l": "즐겁다"},
  {"t": " ", "l": " "},
  {"t": "시간을", "l": "시간"},
  {"t": " ", "l": " "},
  {"t": "보내요", "l": "보내다"},
  {"t": ".", "l": "."}
]'::jsonb
),
(
    '한국의 전통 시장',
    'Pasar Tradisional di Korea',
    'Traditional Markets in Korea',
    '한국의 전통 시장은 현지의 활기찬 분위기와 정을 느낄 수 있는 특별한 곳이에요. 서울의 남대문 시장이나 광장 시장이 대표적이에요. 전통 시장에서는 옷, 그릇, 과일 등 다양한 물건을 저렴하게 살 수 있어요. 특히 떡볶이, 빈대떡, 호떡 같은 맛있는 길거리 음식을 파는 먹자골목이 인기가 많아요. 물건값을 깎아 달라고 흥정하는 재미도 있고, 덤으로 물건을 더 주시는 상인들의 따뜻한 마음도 느낄 수 있어요.',
    'Pasar tradisional di Korea adalah tempat spesial di mana Anda bisa merasakan kehangatan dan atmosfer lokal yang dinamis. Pasar Namdaemun atau Pasar Gwangjang di Seoul adalah contoh yang representatif. Di pasar tradisional, Anda bisa membeli berbagai barang seperti pakaian, peralatan makan, dan buah-buahan dengan harga murah. Secara khusus, gang makanan (Meokja Golmok) yang menjual makanan jalanan lezat seperti Tteokbokki, Bindaetteok, dan Hotteok sangat populer. Selain asyik menawar harga barang, Anda juga bisa merasakan kehangatan para pedagang yang memberikan bonus barang lebih (deom).',
    'Traditional markets in Korea are special places where you can feel the local warm affection and vibrant atmosphere. Namdaemun Market or Gwangjang Market in Seoul are representative examples. In traditional markets, you can buy various items such as clothes, dishes, and fruits at cheap prices. In particular, food alleys selling delicious street food like Tteokbokki, Bindaetteok, and Hotteok are highly popular. It is fun to bargain for prices, and you can also feel the warm hearts of merchants who give extra items for free (deom).',
    'intermediate',
    'travel',
    'https://images.unsplash.com/photo-1590301157890-4810ed352733?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "한국의", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "전통", "l": "전통"},
  {"t": " ", "l": " "},
  {"t": "시장은", "l": "시장"},
  {"t": " ", "l": " "},
  {"t": "현지의", "l": "현지"},
  {"t": " ", "l": " "},
  {"t": "활기찬", "l": "활기차다"},
  {"t": " ", "l": " "},
  {"t": "분위기와", "l": "분위기"},
  {"t": " ", "l": " "},
  {"t": "정을", "l": "정"},
  {"t": " ", "l": " "},
  {"t": "느낄", "l": "느끼다"},
  {"t": " ", "l": " "},
  {"t": "수", "l": "수"},
  {"t": " ", "l": " "},
  {"t": "있는", "l": "있다"},
  {"t": " ", "l": " "},
  {"t": "특별한", "l": "특별하다"},
  {"t": " ", "l": " "},
  {"t": "곳이에요", "l": "곳이다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "서울의", "l": "서울"},
  {"t": " ", "l": " "},
  {"t": "남대문", "l": "남대문"},
  {"t": " ", "l": " "},
  {"t": "시장이나", "l": "시장"},
  {"t": " ", "l": " "},
  {"t": "광장", "l": "광장"},
  {"t": " ", "l": " "},
  {"t": "시장이", "l": "시장"},
  {"t": " ", "l": " "},
  {"t": "대표적이에요", "l": "대표적이다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "전통", "l": "전통"},
  {"t": " ", "l": " "},
  {"t": "시장에서는", "l": "시장"},
  {"t": " ", "l": " "},
  {"t": "옷", "l": "옷"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "그릇", "l": "그릇"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "과일", "l": "과일"},
  {"t": " ", "l": " "},
  {"t": "등", "l": "등"},
  {"t": " ", "l": " "},
  {"t": "다양한", "l": "다양하다"},
  {"t": " ", "l": " "},
  {"t": "물건을", "l": "물건"},
  {"t": " ", "l": " "},
  {"t": "저렴하게", "l": "저렴하다"},
  {"t": " ", "l": " "},
  {"t": "살", "l": "사다"},
  {"t": " ", "l": " "},
  {"t": "수", "l": "수"},
  {"t": " ", "l": " "},
  {"t": "있어요", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "특히", "l": "특히"},
  {"t": " ", "l": " "},
  {"t": "떡볶이", "l": "떡볶이"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "빈대떡", "l": "빈대떡"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "호떡", "l": "호떡"},
  {"t": " ", "l": " "},
  {"t": "같은", "l": "같다"},
  {"t": " ", "l": " "},
  {"t": "맛있는", "l": "맛있다"},
  {"t": " ", "l": " "},
  {"t": "길거리", "l": "길거리"},
  {"t": " ", "l": " "},
  {"t": "음식을", "l": "음식"},
  {"t": " ", "l": " "},
  {"t": "파는", "l": "팔다"},
  {"t": " ", "l": " "},
  {"t": "먹자골목이", "l": "먹자골목"},
  {"t": " ", "l": " "},
  {"t": "인기가", "l": "인기"},
  {"t": " ", "l": " "},
  {"t": "많아요", "l": "많다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "물건값을", "l": "물건값"},
  {"t": " ", "l": " "},
  {"t": "깎아", "l": "깎다"},
  {"t": " ", "l": " "},
  {"t": "달라고", "l": "달다"},
  {"t": " ", "l": " "},
  {"t": "흥정하는", "l": "흥정하다"},
  {"t": " ", "l": " "},
  {"t": "재미도", "l": "재미"},
  {"t": " ", "l": " "},
  {"t": "있고", "l": "있다"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "덤으로", "l": "덤"},
  {"t": " ", "l": " "},
  {"t": "물건을", "l": "물건"},
  {"t": " ", "l": " "},
  {"t": "더", "l": "더"},
  {"t": " ", "l": " "},
  {"t": "주시는", "l": "주다"},
  {"t": " ", "l": " "},
  {"t": "상인들의", "l": "상인"},
  {"t": " ", "l": " "},
  {"t": "따뜻한", "l": "따뜻하다"},
  {"t": " ", "l": " "},
  {"t": "마음도", "l": "마음"},
  {"t": " ", "l": " "},
  {"t": "느낄", "l": "느끼다"},
  {"t": " ", "l": " "},
  {"t": "수", "l": "수"},
  {"t": " ", "l": " "},
  {"t": "있어요", "l": "있다"},
  {"t": ".", "l": "."}
]'::jsonb
),
(
    '서울의 한강 공원',
    'Taman Sungai Han di Seoul',
    'Hangang River Park in Seoul',
    '한강은 서울의 중심을 가로질러 흐르는 강이며, 강을 따라 여러 개의 아름다운 한강 공원이 조성되어 있어요. 주말이면 많은 서울 시민들이 자전거를 타거나 잔디밭에 돗자리를 펴고 피크닉을 즐겨요. 편의점에서 즉석 기계로 끓여 먹는 라면은 한강 공원의 인기 메뉴예요. 치킨이나 피자 같은 배달 음식을 돗자리까지 배달시켜 먹는 것도 특별한 경험이에요. 밤이 되면 한강 다리와 빌딩들이 만드는 화려한 야경을 감상할 수 있어요.',
    'Sungai Han adalah sungai yang mengalir membelah pusat kota Seoul, dan beberapa taman Sungai Han yang indah dibangun di sepanjang sungai tersebut. Di akhir pekan, banyak warga Seoul bersepeda atau menggelar tikar di halaman rumput untuk menikmati piknik. Ramen yang dimasak menggunakan mesin otomatis di minimarket adalah menu populer di taman Sungai Han. Memesan makanan seperti ayam goreng atau pizza untuk diantarkan langsung ke tikar piknik juga merupakan pengalaman unik. Saat malam tiba, Anda bisa menikmati pemandangan malam yang indah dari jembatan Sungai Han dan gedung-gedung tinggi.',
    'The Hangang River is a river that flows across the center of Seoul, and several beautiful Hangang parks are built along the river. On weekends, many Seoul citizens ride bicycles or spread mats on the grass to enjoy a picnic. Ramen cooked using an automatic machine at convenience stores is a popular menu item at Hangang Park. Ordering delivery food like chicken or pizza to be delivered right to your picnic mat is also a unique experience. At night, you can enjoy the gorgeous night view created by the Hangang bridges and buildings.',
    'intermediate',
    'travel',
    'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "한강은", "l": "한강"},
  {"t": " ", "l": " "},
  {"t": "서울의", "l": "서울"},
  {"t": " ", "l": " "},
  {"t": "중심을", "l": "중심"},
  {"t": " ", "l": " "},
  {"t": "가로질러", "l": "가로지르다"},
  {"t": " ", "l": " "},
  {"t": "흐르는", "l": "흐르다"},
  {"t": " ", "l": " "},
  {"t": "강이며", "l": "강"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "강을", "l": "강"},
  {"t": " ", "l": " "},
  {"t": "따라", "l": "따르다"},
  {"t": " ", "l": " "},
  {"t": "여러", "l": "여러"},
  {"t": " ", "l": " "},
  {"t": "개의", "l": "개"},
  {"t": " ", "l": " "},
  {"t": "아름다운", "l": "아름답다"},
  {"t": " ", "l": " "},
  {"t": "한강", "l": "한강"},
  {"t": " ", "l": " "},
  {"t": "공원이", "l": "공원"},
  {"t": " ", "l": " "},
  {"t": "조성되어", "l": "조성되다"},
  {"t": " ", "l": " "},
  {"t": "있어요", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "주말이면", "l": "주말"},
  {"t": " ", "l": " "},
  {"t": "많은", "l": "많다"},
  {"t": " ", "l": " "},
  {"t": "서울", "l": "서울"},
  {"t": " ", "l": " "},
  {"t": "시민들이", "l": "시민"},
  {"t": " ", "l": " "},
  {"t": "자전거를", "l": "자전거"},
  {"t": " ", "l": " "},
  {"t": "타거나", "l": "타다"},
  {"t": " ", "l": " "},
  {"t": "잔디밭에", "l": "잔디밭"},
  {"t": " ", "l": " "},
  {"t": "돗자리를", "l": "돗자리"},
  {"t": " ", "l": " "},
  {"t": "펴고", "l": "펴다"},
  {"t": " ", "l": " "},
  {"t": "피크닉을", "l": "피크닉"},
  {"t": " ", "l": " "},
  {"t": "즐겨요", "l": "즐기다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "편의점에서", "l": "편의점"},
  {"t": " ", "l": " "},
  {"t": "즉석", "l": "즉석"},
  {"t": " ", "l": " "},
  {"t": "기계로", "l": "기계"},
  {"t": " ", "l": " "},
  {"t": "끓여", "l": "끓이다"},
  {"t": " ", "l": " "},
  {"t": "먹는", "l": "먹다"},
  {"t": " ", "l": " "},
  {"t": "라면은", "l": "라면"},
  {"t": " ", "l": " "},
  {"t": "한강", "l": "한강"},
  {"t": " ", "l": " "},
  {"t": "공원의", "l": "공원"},
  {"t": " ", "l": " "},
  {"t": "인기", "l": "인기"},
  {"t": " ", "l": " "},
  {"t": "메뉴예요", "l": "메뉴"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "치킨이나", "l": "치킨"},
  {"t": " ", "l": " "},
  {"t": "피자", "l": "피자"},
  {"t": " ", "l": " "},
  {"t": "같은", "l": "같다"},
  {"t": " ", "l": " "},
  {"t": "배달", "l": "배달"},
  {"t": " ", "l": " "},
  {"t": "음식을", "l": "음식"},
  {"t": " ", "l": " "},
  {"t": "돗자리까지", "l": "돗자리"},
  {"t": " ", "l": " "},
  {"t": "배달시켜", "l": "배달시키다"},
  {"t": " ", "l": " "},
  {"t": "먹는", "l": "먹다"},
  {"t": " ", "l": " "},
  {"t": "것도", "l": "것"},
  {"t": " ", "l": " "},
  {"t": "특별한", "l": "특별하다"},
  {"t": " ", "l": " "},
  {"t": "경험이에요", "l": "경험"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "밤이", "l": "밤"},
  {"t": " ", "l": " "},
  {"t": "되면", "l": "되다"},
  {"t": " ", "l": " "},
  {"t": "한강", "l": "한강"},
  {"t": " ", "l": " "},
  {"t": "다리와", "l": "다리"},
  {"t": " ", "l": " "},
  {"t": "빌딩들이", "l": "빌딩"},
  {"t": " ", "l": " "},
  {"t": "만드는", "l": "만들다"},
  {"t": " ", "l": " "},
  {"t": "화려한", "l": "화려하다"},
  {"t": " ", "l": " "},
  {"t": "야경을", "l": "야경"},
  {"t": " ", "l": " "},
  {"t": "감상할", "l": "감상하다"},
  {"t": " ", "l": " "},
  {"t": "수", "l": "수"},
  {"t": " ", "l": " "},
  {"t": "있어요", "l": "있다"},
  {"t": ".", "l": "."}
]'::jsonb
),
(
    '한류가 한국 경제에 미치는 영향',
    'Dampak Hallyu terhadap Perekonomian Korea',
    'The Influence of Hallyu on the Korean Economy',
    '케이팝, 드라마, 화장품, 한식 등을 아우르는 한류는 단순한 문화적 유행을 넘어 한국 경제의 신성장 동력으로 자리매김하고 있다. 한국 문화 콘텐츠의 글로벌 흥행은 소비재 수출 증가로 직결된다. 예컨대 드라마에 등장한 화장품이나 라면 등이 세계적인 인기를 끌며 수출량이 급증하는 효과를 낳는다. 또한 한국의 이미지 제고는 외래 관광객 유치를 촉진하여 관광 및 서비스 산업 활성화에 기여한다. 그러나 한류에 지나치게 의존하는 경제 구조는 국가 간의 외교적 마찰이나 글로벌 플랫폼의 독점적 규제 등 대외 변수에 취약할 수 있다는 우려도 존재한다. 지속 가능한 경제적 파급 효과를 유지하기 위해서는 콘텐츠의 질적 고도화 and 시장 다변화가 필요하다.',
    'Hallyu yang mencakup K-pop, drama, kosmetik, dan makanan Korea melampaui tren budaya sederhana, memantapkan dirinya sebagai mesin pertumbuhan baru bagi perekonomian Korea. Kesuksesan global konten budaya Korea berdampak langsung pada peningkatan ekspor barang konsumsi. Misalnya, kosmetik atau ramen yang muncul di drama mendapatkan popularitas global dan melipatgandakan volume ekspor. Selain itu, peningkatan citra Korea mendorong penarikan wisatawan asing, berkontribusi pada revitalisasi industri pariwisata dan jasa. Namun, struktur ekonomi yang terlalu bergantung pada Hallyu menimbulkan kekhawatiran karena rentan terhadap variabel eksternal seperti gesekan diplomatik antarnegara atau regulasi monopoli platform global. Untuk mempertahankan dampak ekonomi yang berkelanjutan, peningkatan kualitas konten dan diversifikasi pasar sangat diperlukan.',
    'Hallyu, which encompasses K-pop, dramas, cosmetics, and Korean food, goes beyond a simple cultural trend, establishing itself as a new growth engine for the Korean economy. The global success of Korean cultural content directly leads to an increase in exports of consumer goods. For instance, cosmetics or ramen featured in dramas gain worldwide popularity, producing the effect of skyrocketing export volumes. Moreover, the improvement of Korea''s image promotes attracting foreign tourists, contributing to revitalizing the tourism and service industries. However, there are concerns that an economic structure excessively dependent on Hallyu can be vulnerable to external variables, such as diplomatic friction between countries or monopolistic regulations of global platforms. To maintain sustainable economic spillover effects, high quality content upgrades and market diversification are necessary.',
    'advanced',
    'economy',
    'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "케이팝", "l": "케이팝"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "드라마", "l": "드라마"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "화장품", "l": "화장품"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "한식", "l": "한식"},
  {"t": "등", "l": "등"},
  {"t": "을", "l": "을"},
  {"t": " ", "l": " "},
  {"t": "아우르는", "l": "아우르다"},
  {"t": " ", "l": " "},
  {"t": "한류는", "l": "한류"},
  {"t": " ", "l": " "},
  {"t": "단순한", "l": "단순하다"},
  {"t": " ", "l": " "},
  {"t": "문화적", "l": "문화적"},
  {"t": " ", "l": " "},
  {"t": "유행을", "l": "유행"},
  {"t": " ", "l": " "},
  {"t": "넘어", "l": "넘어"},
  {"t": " ", "l": " "},
  {"t": "한국", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "경제의", "l": "경제"},
  {"t": " ", "l": " "},
  {"t": "신성장", "l": "신성장"},
  {"t": " ", "l": " "},
  {"t": "동력으로", "l": "동력"},
  {"t": " ", "l": " "},
  {"t": "자리매김하고", "l": "자리매김하다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "한국", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "문화", "l": "문화"},
  {"t": " ", "l": " "},
  {"t": "콘텐츠의", "l": "콘텐츠"},
  {"t": " ", "l": " "},
  {"t": "글로벌", "l": "글로벌"},
  {"t": " ", "l": " "},
  {"t": "흥행은", "l": "흥행"},
  {"t": " ", "l": " "},
  {"t": "소비재", "l": "소비재"},
  {"t": " ", "l": " "},
  {"t": "수출", "l": "수출"},
  {"t": " ", "l": " "},
  {"t": "증가로", "l": "증가"},
  {"t": " ", "l": " "},
  {"t": "직결된다", "l": "직결되다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "예컨대", "l": "예컨대"},
  {"t": " ", "l": " "},
  {"t": "드라마에", "l": "드라마"},
  {"t": " ", "l": " "},
  {"t": "등장한", "l": "등장하다"},
  {"t": " ", "l": " "},
  {"t": "화장품이나", "l": "화장품"},
  {"t": " ", "l": " "},
  {"t": "라면", "l": "라면"},
  {"t": "등이", "l": "등"},
  {"t": " ", "l": " "},
  {"t": "세계적인", "l": "세계적"},
  {"t": " ", "l": " "},
  {"t": "인기를", "l": "인기"},
  {"t": " ", "l": " "},
  {"t": "끌며", "l": "끄르다"},
  {"t": " ", "l": " "},
  {"t": "수출량이", "l": "수출량"},
  {"t": " ", "l": " "},
  {"t": "급증하는", "l": "급증하다"},
  {"t": " ", "l": " "},
  {"t": "효과를", "l": "효과"},
  {"t": " ", "l": " "},
  {"t": "낳는다", "l": "낳다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "또한", "l": "또한"},
  {"t": " ", "l": " "},
  {"t": "한국의", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "이미지", "l": "이미지"},
  {"t": " ", "l": " "},
  {"t": "제고는", "l": "제고"},
  {"t": " ", "l": " "},
  {"t": "외래", "l": "외래"},
  {"t": " ", "l": " "},
  {"t": "관광객", "l": "관광객"},
  {"t": " ", "l": " "},
  {"t": "유치를", "l": "유치"},
  {"t": " ", "l": " "},
  {"t": "촉진하여", "l": "촉진하다"},
  {"t": " ", "l": " "},
  {"t": "관광", "l": "관광"},
  {"t": " ", "l": " "},
  {"t": "및", "l": "및"},
  {"t": " ", "l": " "},
  {"t": "서비스", "l": "서비스"},
  {"t": " ", "l": " "},
  {"t": "산업", "l": "산업"},
  {"t": " ", "l": " "},
  {"t": "활성화에", "l": "활성화"},
  {"t": " ", "l": " "},
  {"t": "기여한다", "l": "기여하다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "그러나", "l": "그러나"},
  {"t": " ", "l": " "},
  {"t": "한류에", "l": "한류"},
  {"t": " ", "l": " "},
  {"t": "지나치게", "l": "지나치다"},
  {"t": " ", "l": " "},
  {"t": "의존하는", "l": "의존하다"},
  {"t": " ", "l": " "},
  {"t": "경제", "l": "경제"},
  {"t": " ", "l": " "},
  {"t": "구조는", "l": "구조"},
  {"t": " ", "l": " "},
  {"t": "국가", "l": "국가"},
  {"t": " ", "l": " "},
  {"t": "간의", "l": "사이"},
  {"t": " ", "l": " "},
  {"t": "외교적", "l": "외교적"},
  {"t": " ", "l": " "},
  {"t": "마찰이나", "l": "마찰"},
  {"t": " ", "l": " "},
  {"t": "글로벌", "l": "글로벌"},
  {"t": " ", "l": " "},
  {"t": "플랫폼의", "l": "플랫폼"},
  {"t": " ", "l": " "},
  {"t": "독점적", "l": "독점적"},
  {"t": " ", "l": " "},
  {"t": "규제", "l": "규제"},
  {"t": "등", "l": "등"},
  {"t": " ", "l": " "},
  {"t": "대외", "l": "대외"},
  {"t": " ", "l": " "},
  {"t": "변수에", "l": "변수"},
  {"t": " ", "l": " "},
  {"t": "취약할", "l": "취약하다"},
  {"t": " ", "l": " "},
  {"t": "수", "l": "수"},
  {"t": " ", "l": " "},
  {"t": "있다는", "l": "있다"},
  {"t": " ", "l": " "},
  {"t": "우려도", "l": "우려"},
  {"t": " ", "l": " "},
  {"t": "존재한다", "l": "존재하다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "지속", "l": "지속"},
  {"t": "가능한", "l": "가능하다"},
  {"t": " ", "l": " "},
  {"t": "경제적", "l": "경제적"},
  {"t": " ", "l": " "},
  {"t": "파급", "l": "파급"},
  {"t": " ", "l": " "},
  {"t": "효과를", "l": "효과"},
  {"t": " ", "l": " "},
  {"t": "유지하기", "l": "유지하다"},
  {"t": "위해서는", "l": "위하다"},
  {"t": " ", "l": " "},
  {"t": "콘텐츠의", "l": "콘텐츠"},
  {"t": " ", "l": " "},
  {"t": "질적", "l": "질적"},
  {"t": " ", "l": " "},
  {"t": "고도화", "l": "고도화"},
  {"t": " ", "l": " "},
  {"t": "and", "l": "and"},
  {"t": " ", "l": " "},
  {"t": "시장", "l": "시장"},
  {"t": " ", "l": " "},
  {"t": "다변화가", "l": "다변화"},
  {"t": " ", "l": " "},
  {"t": "필요하다", "l": "필요하다"},
  {"t": ".", "l": "."}
]'::jsonb
),
(
    '한국의 신재생 에너지와 탄소 중립',
    'Energi Baru Terbarukan dan Netralitas Karbon di Korea',
    'Renewable Energy and Carbon Neutrality in Korea',
    '대한민국 정부는 기후변화 대응을 위한 국제 사회의 노력에 발맞추어 2050년까지 실질적인 탄소 배출량을 제로로 만드는 탄소 중립을 선언하였다. 제조업과 중화학공업의 비중이 높은 한국의 산업 구조상 탄소 중립은 매우 도전적인 과제이다. 이에 따라 태양광, 풍력, 수소 에너지 등 신재생 에너지로의 전환을 가속화하고 있다. 노후 화력발전소 폐쇄와 친환경 자동차 보급 확대 등이 주요 정책으로 추진 중이다. 하지만 신재생 에너지의 불완전한 전력 공급 안정성, 발전 설비 설치 과정에서 발생하는 지역 주민들과의 갈등, 그리고 원자력 발전의 활용 비중을 둘러싼 사회적 합의 도출은 해결해야 할 난제이다. 기후 위기 극복과 산업 경쟁력 유지를 모두 달성할 수 있는 정교한 에너지 믹스 전략이 요구된다.',
    'Pemerintah Republik Korea menyatakan netralitas karbon untuk membuat emisi karbon riil menjadi nol pada tahun 2050 sejalan dengan upaya masyarakat internasional merespons perubahan iklim. Mengingat struktur industri Korea yang memiliki proporsi manufaktur dan industri kimia berat yang tinggi, netralitas karbon adalah tugas yang sangat menantang. Oleh karena itu, transisi ke energi baru terbarukan seperti energi surya, angin, dan hidrogen sedang dipercepat. Penutupan pembangkit listrik tenaga uap (PLTU) batu bara yang tua dan perluasan penyebaran kendaraan ramah lingkungan didorong sebagai kebijakan utama. Namun, ketidakstabilan pasokan listrik energi terbarukan, konflik dengan warga lokal dalam proses pemasangan fasilitas pembangkit, serta pencapaian konsensus sosial tentang proporsi penggunaan energi nuklir adalah masalah sulit yang harus diselesaikan. Diperlukan strategi bauran energi (energy mix) yang canggih untuk mengatasi krisis iklim sekaligus mempertahankan daya saing industri.',
    'The government of the Republic of Korea declared carbon neutrality to make net carbon emissions zero by 2050, in line with the international community''s efforts to respond to climate change. Given Korea''s industrial structure with a high proportion of manufacturing and heavy chemical industries, carbon neutrality is a highly challenging task. Accordingly, the transition to renewable energy such as solar, wind, and hydrogen energy is being accelerated. Closing aged coal-fired power plants and expanding the distribution of eco-friendly vehicles are being pursued as key policies. However, the unstable power supply of renewable energy, conflicts with local residents in the process of installing power facilities, and deriving a social consensus on the proportion of nuclear power utilization are difficult tasks to solve. A sophisticated energy mix strategy that can achieve both climate crisis response and industrial competitiveness is required.',
    'advanced',
    'society',
    'https://images.unsplash.com/photo-1466611653911-95081537e5b7?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "대한민국", "l": "대한민국"},
  {"t": " ", "l": " "},
  {"t": "정부는", "l": "정부"},
  {"t": " ", "l": " "},
  {"t": "기후변화", "l": "기후변화"},
  {"t": " ", "l": " "},
  {"t": "대응을", "l": "대응"},
  {"t": " ", "l": " "},
  {"t": "위한", "l": "위하다"},
  {"t": " ", "l": " "},
  {"t": "국제", "l": "국제"},
  {"t": " ", "l": " "},
  {"t": "사회의", "l": "사회"},
  {"t": " ", "l": " "},
  {"t": "노력에", "l": "노력"},
  {"t": " ", "l": " "},
  {"t": "발맞추어", "l": "발맞추다"},
  {"t": " ", "l": " "},
  {"t": "2050년까지", "l": "2050년까지"},
  {"t": " ", "l": " "},
  {"t": "실질적인", "l": "실질적"},
  {"t": " ", "l": " "},
  {"t": "탄소", "l": "탄소"},
  {"t": " ", "l": " "},
  {"t": "배출량을", "l": "배출량"},
  {"t": " ", "l": " "},
  {"t": "제로로", "l": "제로"},
  {"t": " ", "l": " "},
  {"t": "만드는", "l": "만들다"},
  {"t": " ", "l": " "},
  {"t": "탄소", "l": "탄소"},
  {"t": " ", "l": " "},
  {"t": "중립을", "l": "중립"},
  {"t": " ", "l": " "},
  {"t": "선언하였다", "l": "선언하다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "제조업과", "l": "제조업"},
  {"t": " ", "l": " "},
  {"t": "중화학공업의", "l": "중화학공업"},
  {"t": " ", "l": " "},
  {"t": "비중이", "l": "비중"},
  {"t": " ", "l": " "},
  {"t": "높은", "l": "높다"},
  {"t": " ", "l": " "},
  {"t": "한국의", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "산업", "l": "산업"},
  {"t": " ", "l": " "},
  {"t": "구조상", "l": "구조"},
  {"t": " ", "l": " "},
  {"t": "탄소", "l": "탄소"},
  {"t": " ", "l": " "},
  {"t": "중립은", "l": "중립"},
  {"t": " ", "l": " "},
  {"t": "매우", "l": "매우"},
  {"t": " ", "l": " "},
  {"t": "도전적인", "l": "도전적"},
  {"t": " ", "l": " "},
  {"t": "과제이다", "l": "과제이다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "이에", "l": "이에"},
  {"t": " ", "l": " "},
  {"t": "따라", "l": "따르다"},
  {"t": " ", "l": " "},
  {"t": "태양광", "l": "태양광"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "풍력", "l": "풍력"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "수소", "l": "수소"},
  {"t": " ", "l": " "},
  {"t": "에너지", "l": "에너지"},
  {"t": " ", "l": " "},
  {"t": "등", "l": "등"},
  {"t": " ", "l": " "},
  {"t": "신재생", "l": "신재생"},
  {"t": " ", "l": " "},
  {"t": "에너지로의", "l": "에너지"},
  {"t": " ", "l": " "},
  {"t": "전환을", "l": "전환"},
  {"t": " ", "l": " "},
  {"t": "가속화하고", "l": "가속화하다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "노후", "l": "노후"},
  {"t": " ", "l": " "},
  {"t": "화력발전소", "l": "화력발전소"},
  {"t": " ", "l": " "},
  {"t": "폐쇄와", "l": "폐쇄"},
  {"t": " ", "l": " "},
  {"t": "친환경", "l": "친환경"},
  {"t": " ", "l": " "},
  {"t": "자동차", "l": "자동차"},
  {"t": " ", "l": " "},
  {"t": "보급", "l": "보급"},
  {"t": " ", "l": " "},
  {"t": "확대", "l": "확대"},
  {"t": " ", "l": " "},
  {"t": "등이", "l": "등"},
  {"t": " ", "l": " "},
  {"t": "주요", "l": "주요"},
  {"t": " ", "l": " "},
  {"t": "정책으로", "l": "정책"},
  {"t": " ", "l": " "},
  {"t": "추진", "l": "추진"},
  {"t": " ", "l": " "},
  {"t": "중이다", "l": "중이다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "하지만", "l": "하지만"},
  {"t": " ", "l": " "},
  {"t": "신재생", "l": "신재생"},
  {"t": " ", "l": " "},
  {"t": "에너지의", "l": "에너지"},
  {"t": " ", "l": " "},
  {"t": "불완전한", "l": "불완전하다"},
  {"t": " ", "l": " "},
  {"t": "전력", "l": "전력"},
  {"t": " ", "l": " "},
  {"t": "공급", "l": "공급"},
  {"t": " ", "l": " "},
  {"t": "안정성", "l": "안정성"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "발전", "l": "발전"},
  {"t": " ", "l": " "},
  {"t": "설비", "l": "설비"},
  {"t": " ", "l": " "},
  {"t": "설치", "l": "설치"},
  {"t": " ", "l": " "},
  {"t": "과정에서", "l": "과정"},
  {"t": " ", "l": " "},
  {"t": "발생하는", "l": "발생하다"},
  {"t": " ", "l": " "},
  {"t": "지역", "l": "지역"},
  {"t": " ", "l": " "},
  {"t": "주민들과의", "l": "주민"},
  {"t": " ", "l": " "},
  {"t": "갈등", "l": "갈등"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "그리고", "l": "그리고"},
  {"t": " ", "l": " "},
  {"t": "원자력", "l": "원자력"},
  {"t": " ", "l": " "},
  {"t": "발전의", "l": "발전"},
  {"t": " ", "l": " "},
  {"t": "활용", "l": "활용"},
  {"t": " ", "l": " "},
  {"t": "비중을", "l": "비중"},
  {"t": " ", "l": " "},
  {"t": "둘러싼", "l": "둘러싸다"},
  {"t": " ", "l": " "},
  {"t": "사회적", "l": "사회적"},
  {"t": " ", "l": " "},
  {"t": "합의", "l": "합의"},
  {"t": " ", "l": " "},
  {"t": "도출은", "l": "도출"},
  {"t": " ", "l": " "},
  {"t": "해결해야", "l": "해결하다"},
  {"t": " ", "l": " "},
  {"t": "할", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "난제이다", "l": "난제이다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "기후", "l": "기후"},
  {"t": " ", "l": " "},
  {"t": "위기", "l": "위기"},
  {"t": " ", "l": " "},
  {"t": "극복과", "l": "극복"},
  {"t": " ", "l": " "},
  {"t": "산업", "l": "산업"},
  {"t": " ", "l": " "},
  {"t": "경쟁력", "l": "경쟁력"},
  {"t": " ", "l": " "},
  {"t": "유지를", "l": "유지"},
  {"t": " ", "l": " "},
  {"t": "모두", "l": "모두"},
  {"t": " ", "l": " "},
  {"t": "달성할", "l": "달성하다"},
  {"t": " ", "l": " "},
  {"t": "수", "l": "수"},
  {"t": " ", "l": " "},
  {"t": "있는", "l": "있다"},
  {"t": " ", "l": " "},
  {"t": "정교한", "l": "정교하다"},
  {"t": " ", "l": " "},
  {"t": "에너지", "l": "에너지"},
  {"t": " ", "l": " "},
  {"t": "믹스", "l": "믹스"},
  {"t": " ", "l": " "},
  {"t": "전략이", "l": "전략"},
  {"t": " ", "l": " "},
  {"t": "요구된다", "l": "요구되다"},
  {"t": ".", "l": "."}
]'::jsonb
),
(
    '한국 현대 사회의 경쟁과 정신 건강',
    'Persaingan dan Kesehatan Mental di Masyarakat Korea Modern',
    'Competition and Mental Health in Modern Korean Society',
    '한국 현대 사회는 세계적으로 높은 수준의 학업 성취와 급격한 경제 성장을 이룩했지만, 그 이면에는 극심한 경쟁 구도가 자리 잡고 있다. 청소년기부터 입시를 위해 하루 대부분을 공부에 쏟아부어야 하고, 성인이 되어서도 취업과 승진을 위한 무한 경쟁에 노출된다. 이러한 피로 사회의 구조적 환경은 현대인들에게 우울증, 불안 장애 등 심각한 정신 건강 문제를 유발하고 있다. 과거에는 정신과 치료나 심리 상담에 대한 부정적인 사회적 편견 때문에 고통을 숨기는 경우가 많았으나, 최근에는 인식 개선을 통해 스스로 상담을 찾거나 심리적 지원을 요청하는 비율이 늘고 있다. 근본적인 해결을 위해 근로 시간 단축, 워라밸 문화의 정착과 더불어 예방 중심의 정신 복지 인프라 구축이 요구된다.',
    'Masyarakat Korea modern telah mencapai tingkat prestasi akademis yang tinggi dan pertumbuhan ekonomi yang pesat di dunia, namun di balik itu terdapat struktur persaingan yang sangat ketat. Sejak masa remaja, mereka harus menghabiskan sebagian besar hari untuk belajar demi ujian masuk, dan bahkan setelah menjadi dewasa, mereka dihadapkan pada persaingan tanpa batas demi pekerjaan dan promosi. Lingkungan struktural dari "masyarakat lelah" (fatigue society) ini memicu masalah kesehatan mental yang serius seperti depresi dan gangguan kecemasan bagi orang modern. Di masa lalu, banyak yang menyembunyikan penderitaan mereka karena prasangka sosial negatif terhadap perawatan psikiatri atau konseling psikologis, namun baru-baru ini, melalui perbaikan persepsi, proporsi orang yang mencari konseling sendiri atau meminta dukungan psikologis meningkat. Untuk penyelesaian mendasar, pengurangan jam kerja, pemantapan budaya work-life balance, serta pembangunan infrastruktur kesejahteraan mental berbasis pencegahan sangat diperlukan.',
    'Modern Korean society has achieved high levels of academic achievement and rapid economic growth, but behind them lies an intense competitive structure. From adolescence, students must devote most of their day to studying for college entrance exams, and even as adults, they are exposed to endless competition for employment and promotion. This structural environment of a "fatigue society" is causing serious mental health problems, such as depression and anxiety disorders, among modern people. In the past, many hid their suffering due to negative social prejudice against psychiatric treatment or psychological counseling. However, recently, through improved perception, the proportion of people seeking counseling on their own or requesting psychological support has been increasing. For a fundamental resolution, shortening working hours, establishing a work-life balance culture, and building a prevention-oriented mental welfare infrastructure are required.',
    'advanced',
    'society',
    'https://images.unsplash.com/photo-1518495973542-4542c06a5843?q=80&w=400&auto=format&fit=crop',
    TRUE,
    '[
  {"t": "한국", "l": "한국"},
  {"t": " ", "l": " "},
  {"t": "현대", "l": "현대"},
  {"t": " ", "l": " "},
  {"t": "사회", "l": "사회"},
  {"t": "는", "l": "다"},
  {"t": " ", "l": " "},
  {"t": "세계적", "l": "세계적"},
  {"t": "으로", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "높은", "l": "높다"},
  {"t": " ", "l": " "},
  {"t": "수준", "l": "수준"},
  {"t": "의", "l": "의"},
  {"t": " ", "l": " "},
  {"t": "학업", "l": "학업"},
  {"t": " ", "l": " "},
  {"t": "성취", "l": "성취"},
  {"t": "와", "l": "와"},
  {"t": " ", "l": " "},
  {"t": "급격한", "l": "급격하다"},
  {"t": " ", "l": " "},
  {"t": "경제", "l": "경제"},
  {"t": " ", "l": " "},
  {"t": "성장", "l": "성장"},
  {"t": "을", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "이룩", "l": "이룩하다"},
  {"t": "했", "l": "하다"},
  {"t": "지만", "l": "지만"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "그", "l": "그"},
  {"t": " ", "l": " "},
  {"t": "이면", "l": "이면"},
  {"t": "에는", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "극심한", "l": "극심하다"},
  {"t": " ", "l": " "},
  {"t": "경쟁", "l": "경쟁"},
  {"t": " ", "l": " "},
  {"t": "구도", "l": "구도"},
  {"t": "가", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "자리", "l": "자리"},
  {"t": " ", "l": " "},
  {"t": "잡고", "l": "잡다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "청소년기", "l": "청소년기"},
  {"t": "부터", "l": "부터"},
  {"t": " ", "l": " "},
  {"t": "입시", "l": "입시"},
  {"t": "를", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "위해", "l": "위하다"},
  {"t": " ", "l": " "},
  {"t": "하루", "l": "하루"},
  {"t": " ", "l": " "},
  {"t": "대부분", "l": "대부분"},
  {"t": "을", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "공부", "l": "공부"},
  {"t": "에", "l": "에"},
  {"t": " ", "l": " "},
  {"t": "쏟아부어야", "l": "쏟아부어야"},
  {"t": " ", "l": " "},
  {"t": "하고", "l": "하다"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "성인", "l": "성인"},
  {"t": "이", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "되어서도", "l": "되다"},
  {"t": " ", "l": " "},
  {"t": "취업", "l": "취업"},
  {"t": "과", "l": "과"},
  {"t": " ", "l": " "},
  {"t": "승진", "l": "승진"},
  {"t": "을", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "위한", "l": "위하다"},
  {"t": " ", "l": " "},
  {"t": "무한", "l": "무한"},
  {"t": " ", "l": " "},
  {"t": "경쟁", "l": "경쟁"},
  {"t": "에", "l": "에"},
  {"t": " ", "l": " "},
  {"t": "노출", "l": "노출"},
  {"t": "된다", "l": "되다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "이러한", "l": "이러한"},
  {"t": " ", "l": " "},
  {"t": "피로", "l": "피로"},
  {"t": " ", "l": " "},
  {"t": "사회", "l": "사회"},
  {"t": "의", "l": "의"},
  {"t": " ", "l": " "},
  {"t": "구조적", "l": "구조적"},
  {"t": " ", "l": " "},
  {"t": "환경", "l": "환경"},
  {"t": "은", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "현대인", "l": "현대인"},
  {"t": "들에게", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "우울증", "l": "우울증"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "불안", "l": "불안"},
  {"t": " ", "l": " "},
  {"t": "장애", "l": "장애"},
  {"t": " ", "l": " "},
  {"t": "등", "l": "등"},
  {"t": " ", "l": " "},
  {"t": "심각한", "l": "심각하다"},
  {"t": " ", "l": " "},
  {"t": "정신", "l": "정신"},
  {"t": " ", "l": " "},
  {"t": "건강", "l": "건강"},
  {"t": " ", "l": " "},
  {"t": "문제", "l": "문제"},
  {"t": "를", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "유발", "l": "유발하다"},
  {"t": "하고", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "과거", "l": "과거"},
  {"t": "에는", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "정신과", "l": "정신과"},
  {"t": " ", "l": " "},
  {"t": "치료", "l": "치료"},
  {"t": "나", "l": "나"},
  {"t": " ", "l": " "},
  {"t": "심리", "l": "심리"},
  {"t": " ", "l": " "},
  {"t": "상담", "l": "상담"},
  {"t": "에", "l": "에"},
  {"t": " ", "l": " "},
  {"t": "대한", "l": "대하다"},
  {"t": " ", "l": " "},
  {"t": "부정적", "l": "부정적"},
  {"t": "인", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "사회적", "l": "사회적"},
  {"t": " ", "l": " "},
  {"t": "편견", "l": "편견"},
  {"t": "때문", "l": "때문"},
  {"t": "에", "l": "에"},
  {"t": " ", "l": " "},
  {"t": "고통", "l": "고통"},
  {"t": "을", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "숨기는", "l": "숨기다"},
  {"t": " ", "l": " "},
  {"t": "경우", "l": "경우"},
  {"t": "가", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "많았", "l": "많다"},
  {"t": "으나", "l": "으나"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "최근", "l": "최근"},
  {"t": "에는", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "인식", "l": "인식"},
  {"t": " ", "l": " "},
  {"t": "개선", "l": "개선"},
  {"t": "을", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "통해", "l": "통하다"},
  {"t": " ", "l": " "},
  {"t": "스스로", "l": "스스로"},
  {"t": " ", "l": " "},
  {"t": "상담", "l": "상담"},
  {"t": "을", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "찾거나", "l": "찾다"},
  {"t": " ", "l": " "},
  {"t": "심리적", "l": "심리적"},
  {"t": " ", "l": " "},
  {"t": "지원", "l": "지원"},
  {"t": "을", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "요청", "l": "요청"},
  {"t": "하는", "l": "하다"},
  {"t": " ", "l": " "},
  {"t": "비율", "l": "비율"},
  {"t": "이", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "늘고", "l": "늘다"},
  {"t": " ", "l": " "},
  {"t": "있다", "l": "있다"},
  {"t": ".", "l": "."},
  {"t": "\n", "l": "\n"},
  {"t": "근본적", "l": "근본적"},
  {"t": "인", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "해결", "l": "해결"},
  {"t": "을", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "위해", "l": "위하다"},
  {"t": " ", "l": " "},
  {"t": "근로", "l": "근로"},
  {"t": " ", "l": " "},
  {"t": "시간", "l": "시간"},
  {"t": " ", "l": " "},
  {"t": "단축", "l": "단축"},
  {"t": ",", "l": ","},
  {"t": " ", "l": " "},
  {"t": "워라밸", "l": "워라밸"},
  {"t": " ", "l": " "},
  {"t": "문화", "l": "문화"},
  {"t": "의", "l": "의"},
  {"t": " ", "l": " "},
  {"t": "정착", "l": "정착"},
  {"t": "과", "l": "과"},
  {"t": " ", "l": " "},
  {"t": "더불어", "l": "더불어"},
  {"t": " ", "l": " "},
  {"t": "예방", "l": "예방"},
  {"t": " ", "l": " "},
  {"t": "중심", "l": "중심"},
  {"t": "의", "l": "의"},
  {"t": " ", "l": " "},
  {"t": "정신", "l": "정신"},
  {"t": " ", "l": " "},
  {"t": "복지", "l": "복지"},
  {"t": " ", "l": " "},
  {"t": "인프라", "l": "인프라"},
  {"t": " ", "l": " "},
  {"t": "구축", "l": "구축"},
  {"t": "이", "l": "이다"},
  {"t": " ", "l": " "},
  {"t": "요구", "l": "요구"},
  {"t": "된다", "l": "되다"},
  {"t": ".", "l": "."}
]'::jsonb
);